### ISSUE TITLE
Highlights: after changing a highlight style, should that become the default?

### ISSUE THREAD

**Issue by kjantzer** [FolioReader/FolioReaderKit#10]
I'm posting this to start a discussion.

I feel like it would be the most intuitive that if a user adds a highlight, then changes the style to pink, the next applied "highlight" should use pink too until the user selects a different style. So, the highlight style will always default to the last used style.

Thoughts?

**Comment by hebertialmeida** [comment]
I agree with you @kjantzer this should be use the last used style.
