### ISSUE TITLE
Ability to share image quotes

### ISSUE THREAD

**Issue by hebertialmeida** [FolioReader/FolioReaderKit#109]
**Summary**
With this option users can share custom images from quotes.

**Details**
Needs to be a square image, with labels for the quote, book title and author.

Currently when select share from selection menu it will share only text, needs to add two options, "Share image quote" and "Share text quote".

**Notes**
Public api for customization, logo and background images.

**Proposed design**

![screen shot 2016-08-10 at 11 05 55 pm](https://cloud.githubusercontent.com/assets/103670/17576972/1290d672-5f4f-11e6-95e6-1989d0ad652b.png)

**Comment by diyaasmc** [comment]
very nice
