### ISSUE TITLE
Custom Text Overlay

### ISSUE THREAD

**Issue by adammlevy** [FolioReader/FolioReaderKit#113]
Is it possible to overlay a custom view over selected text such as a popover?

**Comment by hebertialmeida** [comment]
Can you provide more details about this, maybe some image of what you want to achieve or how it would work.

Why a popover?

**Comment by adammlevy** [comment]
![7252381360_7d937baa5a](https://cloud.githubusercontent.com/assets/599680/17647508/e881b65c-61a7-11e6-9fee-0e6a91848ab9.jpg)

I am including one example of a popover that is displayed when text is selected.

This would work by providing a delegate callback which included the word selected and a frame representing the location of the word.  The the delegate is called I would like to either overlay something over the word or just highlight the text.

**Comment by hebertialmeida** [comment]
I think this is possible to implement using the new `ClassBasedOnClickListener`, @adammlevy take a look on https://github.com/FolioReader/FolioReaderKit/blob/master/Example/StoryboardExample/ExampleFolioReaderContainer.swift#L24

**Comment by hebertialmeida** [comment]
I will be closing this for now, I think this is solved by `ClassBasedOnClickListener`.
