### ISSUE TITLE
React Native Bridge

### ISSUE THREAD

**Issue by MuffinWithJam** [FolioReader/FolioReaderKit#127]
What do you think about making the bridge to react native?

I tryed to make it using facebook's tutorials to make FolioReader as separate View (like `<FolioReader {parameters}></FolioReader>`, but it turned for me to be a bit more complex than i expected, due my zero skills at Swift :sweat_smile:

**Comment by hebertialmeida** [comment]
There is here, but I have never tested to be honest https://github.com/FolioReader/react-native-folio-reader

**Comment by MuffinWithJam** [comment]
@hebertialmeida, don't look like a React Native project, it's more like starter skeleton. Anyway, it's not working for me

**Comment by hebertialmeida** [comment]
Sorry, I have never used this, some one needed and have created. Recently we added a port for NativeScript https://github.com/FolioReader/nativescript-epub

For React Native I will fix and implement it in future but for now I have to finish some implementations on Swift version. If you could help will be perfect.
