### ISSUE TITLE
Build on XCode 8 

### ISSUE THREAD

**Issue by j4zzcat** [FolioReader/FolioReaderKit#129]
How to build on XCode 8 (beta 6, in my case) for iOS 10 ?

**Comment by hebertialmeida** [comment]
It is not converted yet, I have to migrate the project to swift 3 and XCode 8, I will probably do it during  this month.

**Comment by hebertialmeida** [comment]
You can build on Xcode 8 now, but using Swift 2.3 on branch `swift23`. I am working on Swift 3 migration

Use it like this:
```ruby
pod 'FolioReaderKit' :git => 'https://github.com/FolioReader/FolioReaderKit.git', :branch => 'swift23'
```
