### ISSUE TITLE
Scroll to a specific page and specific page number

### ISSUE THREAD

**Issue by sam961** [FolioReader/FolioReaderKit#130]
Hello,
I make a highlight for a specific page and page number and saved it . How to scroll to to this specific page and page number without href since i had not selected any text as an ID for it . I need only to scroll to this page  and pagenumber

**Comment by hebertialmeida** [comment]
I have recently merged a PR #128 from @tschob that exposes this methods. Take a look if it works for you, it on branch master.

**Comment by hebertialmeida** [comment]
Closing this issue, I think this is already possible with new public APIs, feel free to open it again.
