### ISSUE TITLE
Support Highlights which are stored outside of the FolioReaderKit

### ISSUE THREAD

**Issue by tschob** [FolioReader/FolioReaderKit#131]
Provide an interface which enables external code to handle the Highlight persistation.
The database from the FolioReaderKit can be the default option but its implementation should use the new interface as well.

**Comment by hebertialmeida** [comment]
Interesting, today is possible to manage the highlights of FolioReaderKit DB, because it is exposed, you can add, remove, list all...

What do you need is to provide a list of highlights on book initialisation from a external source?

**Comment by tschob** [comment]
We need to store the highlights in our own database. My idea is that a new class like `HighlightModel` or protocol like `Highlightable` is introduced which contains the needed properties.
The `FolioReaderKit` (or another useful place) will hold a delegate which will provide a list of highlights and which receives a new highlight. If this delegate isn't used in app the FolioReaderKit will receive and store the highlights in it's own database.

**Comment by hebertialmeida** [comment]
This is great.

**Comment by danfsd** [comment]
This is a great request. I've been working locally with Highlights outside of the Framework (stored on a server that is accessible via a webservice).

As most HTTP requests are made **asynchronously** it's needed a support to refresh the `FolioReaderPage` looking for new highlights.

Here's a snippet of the code I created to make this possible

```swift
public func insertHighlights(highlights: [Highlight]) {
        if let currentHtml = webView.js("document.documentElement.outerHTML") as? NSString {
            var newHtml = currentHtml.copy() as! NSString
            var didChanged = false
            
            for highlight in highlights {
                if let _ = Highlight.findByHighlightId(highlight.highlightId) {
                    print("Found highlight with id \(highlight.highlightId), skipping...")
                } else {
                    if highlight.page != pageNumber {
                        print("Didn't found highlight with id \(highlight.highlightId) but it's from another page: \(highlight.page)")
                    } else {
                        print("Didn't found highlight with id \(highlight.highlightId). Adding it to the new HTML...")
                        let highlightTag = createHighlightTag(highlight)
                        let range: NSRange = newHtml.rangeOfString(highlightTag.locator, options: .LiteralSearch)
                        if range.location != NSNotFound {
                            let newRange = NSRange(location: range.location + highlight.contentPre.characters.count, length: highlight.content.characters.count)
                            newHtml = newHtml.stringByReplacingCharactersInRange(newRange, withString: highlightTag.tag)
                        }
                        
                        highlight.persist()
                        didChanged = true
                    }
                }
            }
            
            if didChanged {
                webView.loadHTMLString(newHtml as String, baseURL: baseURL)
            }
        }
    }
```

**Comment by hebertialmeida** [comment]
@tschob What you thing about @danfsd solution? May be a first step to that...

**Comment by tschob** [comment]
My approach will indeed be partly similar to @danfsd solution. As the highlights from our app are too diferent to the ones from the Folio Reader we decided that it would be better to add some apis to the Folio Reader which enables us to implement the hightlight in the outside of the Folio Reader.
Therefore we need to modify the HTML string before it's loaded (maybe also to insert a custom Java Script bridge), create custom `UIMenuController` items and add custom on click listeners to specific classes (it's already possible with https://github.com/FolioReader/FolioReaderKit/issues/132).

**Comment by hebertialmeida** [comment]
I think this is already supported.
