### ISSUE TITLE
Perform a custom block if a link with specified class + parameter name is tapped.

### ISSUE THREAD

**Issue by tschob** [FolioReader/FolioReaderKit#132]
We want to perform some logic if a specific custom link is tapped. 

The link in the epub might look like this:
```
<a class="tooltips" href="#" data-json='<some json data>' > + </a>
```
If this link is tapped we want to receive the json data from `data-json` in a closure so that we can perform some logic.

To archive this a new array will be added to the `FolioReaderConfig` containing multiple class + parameter combinations which should be monitored plus the corresponding closure. 

The creation of item might look like this:
```
ListenerCofiguration(classNameValue: "tooltips", parameterNameValue: "data-json", onTap: onTapClosure)
```

**Comment by tschob** [comment]
This issue is now in progress.

**Comment by hebertialmeida** [comment]
This is cool, we will have to start a docs with sample usage, we already have in code documentation but we need something that generate web pages from MD files or something like that.

LinkedIn uses https://readthedocs.org for this https://linkedin.github.io/RocketData/index.html what your guys think?

**Comment by hebertialmeida** [comment]
Just opened #135
