### ISSUE TITLE
Make settings from the font menu accessable to external code 

### ISSUE THREAD

**Issue by tschob** [FolioReader/FolioReaderKit#133]
It should be possible to set the settings which are accessable in the fonts menu from external code. A modification of these should update the webview of the current page.

**Comment by hebertialmeida** [comment]
Today all settings are stored in user defaults, we can simply expose the the static var for that:
https://github.com/FolioReader/FolioReaderKit/blob/master/Source/FolioReaderKit.swift#L108

**Comment by tschob** [comment]
Yes, this is my approach as well.

**Comment by tschob** [comment]
Jsut exposing the static vars won't be enough as the changes of these properties doesn't refresh the UI. I have to encapsulate most of the logic from `FolioReaderFontsMenu` into a manager or helper which reacts on changes from the static vars.

The `FolioReaderFontsMenu` would then only change the static vars (as custom external code) and the manager / helper will update the UI (like it's down now in `FolioReaderFontsMenu`).

**Comment by tschob** [comment]
This issue is now in progess

**Comment by tschob** [comment]
This should be done with https://github.com/FolioReader/FolioReaderKit/pull/138
