### ISSUE TITLE
Provide a way to block the user from leaving a specific `FolioReaderPage`

### ISSUE THREAD

**Issue by tschob** [FolioReader/FolioReaderKit#134]
This might be a rare use case: We want to be able to jump to a specific `FolioReaderPage` in an epub which the user shouldn't be able to leave.

I see two possible ways:
a) Expose the `FolioReaderCenter`s `collectionView` to external code. So we could disable the scrolling.
b) Add property / method / parameter which disabled the scrolling of the collection view. It would be possible to scroll through one `FolioReaderPage`, but not to another one.

I don't really have a preference yet. What do you think @hebertialmeida?

**Comment by kjantzer** [comment]
@tschob - When you say "scroll through one page" are you referring to what would normally be a chapter?

**Comment by tschob** [comment]
@kjantzer Yes, one `FolioReaderPage`.

**Comment by kjantzer** [comment]
I think making it a config/parameter to disable the auto turn to next page/chapter.

**Comment by tschob** [comment]
And the auto turn disabling would be implemented by setting `collectionView.scrollEnabled` to `false`, or do you another way?

I tested this approach shortly and it looked like it works without side effects.

**Comment by kjantzer** [comment]
Yes, I think that's all that would be needed. I don't think it should create any problems.

Probably a good idea to add a config param and a public method for changing the setting even after an epub is open.

**Comment by hebertialmeida** [comment]
Yeah a config would be nice, simple to use.
