### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by hebertialmeida** [FolioReader/FolioReaderKit#135]
I have configured initially http://folioreaderkit.readthedocs.io/ but need to star writing...

**Comment by hebertialmeida** [comment]
As we are using Jazzy, maybe we can do like http://reswift.github.io/ReSwift/master/

**Comment by revolter** [comment]
Did you consider using [GitBook](https://www.gitbook.com)?

**Comment by revolter** [comment]
The `Install in Dash` button from your last link is great!

**Comment by hebertialmeida** [comment]
@revolter GitBook is great, but it is paid...

**Comment by revolter** [comment]
Only if you want private books and/or custom domain. And it looks like it's free for OSS.

**Comment by hebertialmeida** [comment]
I will take a look

**Comment by revolter** [comment]
I first saw it [used by Lacona](https://docs.lacona.io) and found it simpler than readthedocs. And what I love the most is the ability for a user to add a comment to any paragraph, which looks like a GitHub issue which can be replied and closed. Depending on my time, I'd be up to help with it.

**Comment by hebertialmeida** [comment]
We are using cocoadocs for now.
