### ISSUE TITLE
Bug: deleting visible highlight from tableview crashes if trying to delete again from text view

### ISSUE THREAD

**Issue by kjantzer** [FolioReader/FolioReaderKit#14]
If you can see a highlight in the text (current chapter) then you delete that highlight from the table view and return back to the text view, the highlight is still visible. If you try to edit the highlight, such as deleting it, the app will crash.

This makes sense, as the highlight no longer exists.

The current chapter highlights should be refreshed once one is deleted to keep this from happening.

![bug mov](https://cloud.githubusercontent.com/assets/467487/12068654/8d216552-afc6-11e5-8ab0-2b0285253f98.gif)

**Comment by kjantzer** [comment]
Interestingly, performing these actions on the "Sharing Hope" app does not crash the app.

Although the highlight is still visible until reloading that chapter which is not ideal.

**Comment by hebertialmeida** [comment]
@kjantzer I think that this is solved

**Comment by kjantzer** [comment]
Awesome. I'll pull and test it tomorrow. 






On Sun, Jan 3, 2016 at 3:46 PM -0800, "Heberti Almeida" <notifications@github.com> wrote:












@kjantzer I think that this is solved
