### ISSUE TITLE
Support multiple instances of the FolioReader

### ISSUE THREAD

**Issue by tschob** [FolioReader/FolioReaderKit#140]
Adjust the code to support multiple instances of a FolioReader. The `sharedInstances` have to be replaced with a diferent implementation therefore.

**Comment by hebertialmeida** [comment]
I do not understand why, can provide more context?

**Comment by tschob** [comment]
We need two readers on diferent places in the app. But we may could use `FolioReader.sharedInstance.readerContainer = reader` in this case - We have to check it.

Nonetheless it's currently not possible to dispaly two diferent Folio Readers in a app. I think that there is no need to let the reader be a singleton - except that the current implementation uses it as a shortcut. And there are multiple use cases which aren't possible because of the singleton pattern.  One use case could be that two readers should be displayed side by side to provide a comparison of epbus.

**Comment by tschob** [comment]
With the current implementation and `olioReader.sharedInstance.readerContainer = currentReader` most of the font preferences aren't changed in the second reader instance, but the background of the page indactor is.

**Comment by hebertialmeida** [comment]
Makes sense, to use in these cases we will have to refactor the singleton. Also maybe we can simplify the ReaderCenter and ReaderContainer, this is a legacy because of the left side menu, now I think we can simplify that.

**Comment by tschob** [comment]
Is now in active development by @kevindelord
