### ISSUE TITLE
Show image in full screen, like iBook, when double-tapped

### ISSUE THREAD

**Issue by benyboariu** [FolioReader/FolioReaderKit#142]
This nice feature is missing: when user double-taps on an image, show that image in full screen, like iBook is doing
<img width="2057" alt="screen shot 2016-09-14 at 15 01 43" src="https://cloud.githubusercontent.com/assets/958322/18511439/5a11974a-7a8c-11e6-8c26-22e2d40540fa.png">

**Comment by hebertialmeida** [comment]
Yeah, this is ca nice feature, added to the list. Feel free to help us on this 😄

**Comment by benyboariu** [comment]
@hebertialmeida As I know, in the zip I sent you some months ago, that feature was implemented. Please check ;)

**Comment by EmersonCarpes** [comment]
@benyboariu I'm checking this, I must finish this implementation this week...I need put some code with yours.

**Comment by risechen** [comment]
@EmersonCarpes When will you finish the implementation of this feature

**Comment by EmersonCarpes** [comment]
@risechen I haven't a deadline yet, I faced some issues to implement this feature and at moment I'm working in another things. If you want might I could send you the bundle of code to you.

**Comment by risechen** [comment]
@EmersonCarpes Please send the bundle of code to rise_chen@qq.com，Thank you!

**Comment by EmersonCarpes** [comment]
@risechen I had sent you by we transfer.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
