### ISSUE TITLE
Crash at file open

### ISSUE THREAD

**Issue by ProudOfZiggy** [FolioReader/FolioReaderKit#144]
Maybe its a result of iOS 10 SDK but... It crashing while trying to open a file with next message:

2016-09-15 16:26:27.980 MyApp[13190:162705] [SSZipArchive] Error: The file “9781491917480CH02.epub” couldn’t be saved in the folder “Documents” because a file with the same name already exists.
2016-09-15 16:26:27.983 MyApp[13190:162705] [SSZipArchive] Error: The file “9781491917480CH02.epub” couldn’t be saved in the folder “Documents” because a file with the same name already exists.
Cannot read container.xml
fatal error: unexpectedly found nil while unwrapping an Optional value

In FolioReaderContainer 108:
book = FREpubParser().readEpub(epubPath: epubPath!, removeEpub: self.shouldRemoveEpub)

I store all downloaded files in Documents directory. So SSZipArchiver can't copy file in documents folder anymore and FolioReader getting nil epub file path.

**Comment by ProudOfZiggy** [comment]
Even if I'm using other directory. Like Documents/Books I still have the same issue.

**Comment by ProudOfZiggy** [comment]
It seems that initial reason in readContainer() which giving me:
Cannot read container.xml

**Comment by ProudOfZiggy** [comment]
This one always throws an exception:

let containerData = try NSData(contentsOfFile: (bookBasePath as NSString).stringByAppendingPathComponent(containerPath), options: .DataReadingMappedAlways)

**Comment by ProudOfZiggy** [comment]
P.S. Tested on iOS 9 SDK (Xcode 7.3.1) - everything is ok
iOS 10 SDK - Exception.

**Comment by hebertialmeida** [comment]
Can you send me the book? So I can debug that.

**Comment by ProudOfZiggy** [comment]
I've tested with a lot of different books. Unfotunately can't provide you a book =( But with iOS 9 sdk all working well

**Comment by foosaa** [comment]
Cannot read container.xml
fatal error: unexpectedly found nil while unwrapping an Optional value

xcode 7.1.3  iOS 8.1.3

**Comment by ProudOfZiggy** [comment]
Using SSZipArchive version 1.5 didn't work for me.

**Comment by hebertialmeida** [comment]
Sorry guys, I am merging the PR from @tschob and I have fixed Podfile.lock

Releasing a new version ASAP.
