### ISSUE TITLE
Swift 3 migration

### ISSUE THREAD

**Issue by hebertialmeida** [FolioReader/FolioReaderKit#148]

**Comment by tschob** [comment]
@hebertialmeida What's the plan after the migration to Swift 3 is done: Will Swift 2.2. and Swift 2.3 be updated to with fixes and new featuers? Or will they stay like they are now and all development will just take place based on the Swift 3 branch?

**Comment by hebertialmeida** [comment]
For me it is impossible to maintain multiple versions, so basically what I will do is same as many libraries does, When migrated to Swift 3 on a branch It will take place on master, the development will continue.

Sample: https://github.com/Alamofire/Alamofire

Users will be able to use in Swift 2.2, 2.3 and 3 specifying it in Cocoapods, but the last version will be in 3.0 as it is the language evolution.

I did the same from Swift 1 to 2.

**Comment by tschob** [comment]
Ok. So new PRs should better wait for the Swift 3 migration to be done? Do you have an idea when the migration is done?

**Comment by hebertialmeida** [comment]
It is everything working on Swift 2.3 already, just found this bug #152. When it is fixed I will start the migration to version 3, by the end of week or next week.

**Comment by hebertialmeida** [comment]
There is a working version on `swift3` branch, also `swift23`.

Now it needs test, because there is a lot of changes...

**Comment by hebertialmeida** [comment]
Closed by PR #162
