### ISSUE TITLE
UIMenuItem White Color

### ISSUE THREAD

**Issue by sam961** [FolioReader/FolioReaderKit#158]
Hello,
When I had updated to ios 10 , UIMenuitem  images became white color.
any one else faced the problem?
![simulator screen shot sep 26 2016 12 11 25 pm](https://cloud.githubusercontent.com/assets/4921874/18828895/907c7002-83e2-11e6-91d7-089024bd11d0.png)

**Comment by hebertialmeida** [comment]
Hey @sam961, yeah, I have noticed that. This is a problem with UIMenu library https://github.com/cxa/UIMenuItem-CXAImageSupport/issues/9

I will be working on this to fix, the problem is that this lib is deprecated and the new one we had problem on its implementation.
