### ISSUE TITLE
Problem with split view in iPad

### ISSUE THREAD

**Issue by socquique** [FolioReader/FolioReaderKit#160]
Hi guys,

I'm experiencing a problem when try to use the split view in iPad. This is what I'm trying to do to fix it but doesn't work well. Could you help me with that? In FolioReaderCenter.swift I have override the viewWillTransitionToSize and implemented the calls to device orientation changes. This works well for rotations, but no for screen size changes.

```
override public func viewWillTransitionToSize(size: CGSize, withTransitionCoordinator coordinator: UIViewControllerTransitionCoordinator) {
        //super.viewWillTransitionToSize(size, withTransitionCoordinator: coordinator)

        //The device has already rotated, that's why this method is being called.
        var toOrientationDevice = UIDevice.currentDevice().orientation
        var toOrientation = UIInterfaceOrientation.Portrait
        //fixes orientation mismatch (between UIDeviceOrientation and UIInterfaceOrientation)
        if toOrientationDevice.rawValue == UIDeviceOrientation.LandscapeRight.rawValue {
            toOrientation = UIInterfaceOrientation.LandscapeLeft
        }
        else if toOrientationDevice.rawValue == UIDeviceOrientation.LandscapeLeft.rawValue {
            toOrientation = UIInterfaceOrientation.LandscapeRight
        }

        var fromOrientation = UIApplication.sharedApplication().statusBarOrientation

        self.willRotateToInterfaceOrientation(toOrientation, duration: 0.4)

        coordinator.animateAlongsideTransition({ context in
            // do whatever with your context
            self.willAnimateRotationToInterfaceOrientation( toOrientation, duration: context.transitionDuration())
            }, completion: { context in
                // do whatever with your context
                self.didRotateFromInterfaceOrientation(fromOrientation)

        })
    }
```

Thanks in advance!

**Comment by hebertialmeida** [comment]
I have never implemented this, any success on this implementation?

**Comment by socquique** [comment]
As I said, it works fine for device orientation changes, but not for split view changes. 
All help is welcome.

**Comment by PravinNagargoje** [comment]
Works fine for me on split view. Can describe exactly whats problem you are facing?

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
