### ISSUE TITLE
UISearchBar causes error after appearing of FolioReaderContainer

### ISSUE THREAD

**Issue by tiana890** [FolioReader/FolioReaderKit#163]
I have a collection in my UIViewController and UISearchBar above it. When I tap on some cell and present FolioReader, then close it - I have some issues with UISearchBar. If I try to resignFirstResponder on UISearchBar my App fails. 
I tried to present another controller and everything was ok.
May be if I figure out some internal features of FolioReader I can find what's wrong. Perhaps some kind people can help me.

**Comment by hebertialmeida** [comment]
Could you post a sample code, so it will be easy to understand what is happening.

**Comment by tiana890** [comment]
//ListViewController.swift

    //...
    @IBOutlet var searchBar: UISearchBar!
    overrided func  viewDidLoad(){
        //...
        openBook()
    }
    
    func openBook(){
        let config = FolioReaderConfig()
        config.scrollDirection = .horizontal
        
        if let bookPath = self.path{
            FolioReader.presentReader(parentViewController: self, withEpubPath: bookPath, andConfig: config)
        }
    }

    func hideSearch(){
    //....
        self.search.resignFirstResponder()
    }
When the FolioReader is dismissed I call hideSearch() and the app crashes.

**Comment by Skyna** [comment]
I got the same issue. This is how my view is structured.

The cell within the UITableViewController contains UICollectionViews. And there is a UISearchbar in the UINavigationBar. When i open e ePub file and then close it and then tap the UISearchBar. The app crashes and gives this error message.

[57457:2336266] *** -[FolioReaderKit.FolioReaderCenter respondsToSelector:]: message sent to deallocated instance 0x7fe1dd85ec00

**Comment by hebertialmeida** [comment]
@Skyna Could you please create a sample project simulating your project, with tableView and collectionViews + SearchBar?

**Comment by hebertialmeida** [comment]
Also test my latest commits on master branch.

**Comment by Skyna** [comment]
@hebertialmeida i made a test project and i was able to create the bug again. However this time Xcode shows exactly where the error is. (I hope it is the same error as i had)
<img width="1113" alt="screen shot 2016-10-11 at 15 21 11" src="https://cloud.githubusercontent.com/assets/3736780/19271784/670deba2-8fc6-11e6-8ea4-083090f89db5.png">

You can download the this project here:

https://www.dropbox.com/s/sgrk72qy3dwq6hh/FolioReaderBug.zip?dl=0

To create this bug follow these steps:
1. Tap on a cell so the ePub shows up
2. Close the reader
3. Tap on the search icon so the UISearchBar showns up and gets a focus
4. While the UISearchBar is the first responder. Tap on a cell again.
5. It should have crashed now

**Comment by tiana890** [comment]
@hebertialmeida I have tested your fix and everything works fine. Thank u very much.

**Comment by hebertialmeida** [comment]
@tiana890 NP 😄 
@Skyna Make sure you are using the latest master commit, because your code from print screen is different from the master. It is not released yet.

**Comment by Skyna** [comment]
@hebertialmeida My project is build in Swift 2.3 so i use the swift23 branch.

**Comment by hebertialmeida** [comment]
Swift 2.3 will not be maintained anymore, from now only swift 3 will be updated. But you can copy the fix from master and test it.

**Comment by Skyna** [comment]
@hebertialmeida i see. Okej, thanks for your help :)
