### ISSUE TITLE
Crash if "Cannot read container.xml"

### ISSUE THREAD

**Issue by benyboariu** [FolioReader/FolioReaderKit#164]
I found a crash. If `readContainer()` method fails, then `readOpf()` will crash in this line:
`let opfPath = (bookBasePath as NSString).appendingPathComponent(book.opfResource.href)
`
Cause: `fatal error: unexpectedly found nil while unwrapping an Optional value`

The problem I see is that `readContainer()` is not throwing. In my opinion, it should throw, because you have there a do/catch, but if an error is caught, you still continue going on with `readOpf()`, which will crash because `.href` is nil.

<img width="2082" alt="screen shot 2016-10-06 at 22 49 08" src="https://cloud.githubusercontent.com/assets/958322/19168130/5140dfa8-8c17-11e6-9a06-aab93c3105f0.png">

**Comment by hebertialmeida** [comment]
Yes you are right, `readContainer()` needs throw. Actually the `readEpub` need to be failable. Did you fixed this?

**Comment by PravinNagargoje** [comment]
Hey, I have solved this issue and made PR.
