### ISSUE TITLE
How can I use it in xCode8?

### ISSUE THREAD

**Issue by CeeYang** [FolioReader/FolioReaderKit#165]
I have update my cocoapod,and pod it with 'FolioReaderKit', '~> 0.8',set the Swift Version 2.3,But it doesn't work.
The Error Msg is : 
"
ld: /Users/pro/Library/Developer/Xcode/DerivedData/EpubTest-bhhkedjkerjdatfpbfkkskujtjlq/Build/Products/Debug-iphonesimulator/AEXML/AEXML.framework/AEXML compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
"
How can I sove this problem? 
Thanks!

**Comment by hebertialmeida** [comment]
For Xcode 8 and Swift 3 use ~>1.0.0, take a look on releases https://github.com/FolioReader/FolioReaderKit/releases

**Comment by payalbaldota** [comment]
Any updates on this? I am also getting the error for many dependent frameworks for still using Swift 2.3. My OS version is 10.11.6. I am trying to build the Example provided in version 1.0.0 on Xcode 8.0
