### ISSUE TITLE
Night mode tint color, menu text color

### ISSUE THREAD

**Issue by tomasgibas** [FolioReader/FolioReaderKit#166]
It would be great if there is possibility to also set tint color, text color, or highlighted text color in night mode. For example tint color of bar button items in navigation bar.

**Comment by hebertialmeida** [comment]
Do you want a different tintColor while in night mode?

**Comment by hebertialmeida** [comment]
there is a parameter for setting these colors, https://github.com/FolioReader/FolioReaderKit/blob/master/Source/FolioReaderConfig.swift#L106
