### ISSUE TITLE
cannot open epub file

### ISSUE THREAD

**Issue by alexwillrock** [FolioReader/FolioReaderKit#167]
i download epub file from link , and want to open it in this framework, but see empty text in chapters and full list of chapters. (epub 2) file

after i go to documents folder and open epub file from iBooks, and iBooks work.

example epub file [314093.epub.zip](https://github.com/FolioReader/FolioReaderKit/files/519549/314093.epub.zip)

where I made a mistake ?

my open code is 
`    NSString *uid = [_presenter getUid];
    NSString *docsPath = [NSString stringWithFormat:@"%@/Documents", NSHomeDirectory()];
    NSString *fp = [[NSBundle bundleWithPath:docsPath] pathForResource:uid ofType:@"epub"];
    FolioReaderConfig *config = [[FolioReaderConfig alloc] init];
    [FolioReader presentReaderWithParentViewController:self withEpubPath:fp andConfig:config shouldRemoveEpub:true animated:true];`

![simulator screen shot 10 oct 2016 20 15 11](https://cloud.githubusercontent.com/assets/6507402/19237489/481d2a90-8f27-11e6-8378-9c5e20c5411c.png)
![simulator screen shot 10 oct 2016 20 15 18](https://cloud.githubusercontent.com/assets/6507402/19237490/482b2636-8f27-11e6-938f-d9450b1aadad.png)

**Comment by hebertialmeida** [comment]
You have send me the unzipped pub, can you send it again?

**Comment by alexwillrock** [comment]
for example http://napoiske.ru/b/417484.epub
iOS 9+

**Comment by mahavir-jain** [comment]
@hebertialmeida on both iOS and Android, it is showing empty pages.. But when we remove following lines from html files of epub, it works..

<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title/>
<link rel="stylesheet" href="style.css" type="text/css"/>
<link rel="stylesheet" href="style.css" type="text/css"/>
</head>

Seems like some CSS problem..

I hope this hint will help you to solve the issue..

**Comment by hebertialmeida** [comment]
@mahavir-jain Yeah, this is the problem, it has duplicated tags and the title tags is closed wrong. This is not a FolioReader problem, but webView can not parse this html.

@alexwillrock try to use a validator http://validator.idpf.org

**Comment by payalbaldota** [comment]
@hebertialmeida 
[Wildlife%20Adventure.zip](https://github.com/FolioReader/FolioReaderKit/files/763249/Wildlife.20Adventure.zip) 
when we pass this file to FolioReader framework, empty file is displayed. We have validated the file using the link you provided. Can you please check what is the issue with the file. Why FolioReaderKit famework is not able to display it? as per our debugging file gets parsed correctly.
