### ISSUE TITLE
The app sometimes crashes when I try to present FolioReader for not first time

### ISSUE THREAD

**Issue by tiana890** [FolioReader/FolioReaderKit#168]
My controller code:

     //....
     override func viewDidLoad() {
     super.viewDidLoad()
      //...
      openBook()
    }
 
    //MARK: Logic
    func openBook(){
        
        if let bookPath = self.path{
            let config = FolioReaderConfig()
            FolioReader.presentReader(parentViewController: self, withEpubPath: bookPath, andConfig: config)
        }
    }
    
    @IBAction func openEPubPressed(_ sender: AnyObject) {
        openBook()
    }

When I open the book for the first time it is OK. But when I close reader and press openBook again it fails sometimes but sometimes not. Can not understand what is the reason of such behaviour. I get the crash in FolioReaderCenter.swift:
<img width="625" alt="2016-10-11 19 04 19" src="https://cloud.githubusercontent.com/assets/2170659/19273328/8f482d52-8fe5-11e6-81dd-d1fa2ffb7c4f.png">

**Comment by hebertialmeida** [comment]
Fixed.
