### ISSUE TITLE
return readerConfig.shouldHideNavigationOnTap == false ? false : shouldHideStatusBar

### ISSUE THREAD

**Issue by hoosrightapp** [FolioReader/FolioReaderKit#169]
![screen shot 2016-10-21 at 1 00 22 pm](https://cloud.githubusercontent.com/assets/15337033/19590229/5d7bb478-978e-11e6-82cc-cf8f4ac03c0a.png)

Swift 3 getting this error

**Comment by hebertialmeida** [comment]
Could you provide more details and steps to reproduce that...

**Comment by hebertialmeida** [comment]
This should be fixed on latest version.
