### ISSUE TITLE
Add support for ePub 3.0 books

### ISSUE THREAD

**Issue by hebertialmeida** [FolioReader/FolioReaderKit#17]
On epub 3 the toc.ncx file was deprecated, in order do read this new format we need to make this verifications and parse the new toc file. To support both formats.

**Comment by kjantzer** [comment]
@hebertialmeida what replaces the ` toc.ncx` file? Is it still `XML`?

**Comment by hebertialmeida** [comment]
I found this comparison article https://www.safaribooksonline.com/blog/2011/06/14/ncx-into-epub3/

The TOC file is now a HTML file reference on OPF file, I think that we can still use the same xml library to extract the new toc from html.
https://github.com/IDPF/epub3-samples/blob/master/30/moby-dick-mo/OPS/package.opf#L43
https://github.com/IDPF/epub3-samples/blob/master/30/moby-dick-mo/OPS/package.opf#L343

Here is the new *toc.xhtml* sample file
https://github.com/IDPF/epub3-samples/blob/master/30/moby-dick-mo/OPS/toc.xhtml

There is a sample book from IDPF available to download:
https://drive.google.com/uc?export=download&id=0B9g8D2Y-6aPLWXZsaXBsd2hoRnM

There are more samples here: http://idpf.github.io/epub3-samples/samples.html

**Comment by hebertialmeida** [comment]
The sample above includes "Media Overlays" in the first 2 chapters, I have tested it on Readium.
