### ISSUE TITLE
Install version with swift3

### ISSUE THREAD

**Issue by makaGeroge** [FolioReader/FolioReaderKit#171]
Hello, I'm trying to install FolioReaderKit version 1.0.0 but the pod file gives an error. I downloaded the 1.0.0 release and I see I have to install all the dependencies manually. Is there an easy way to download a fully working version for swift3?

Thanks,

Jorge

**Comment by hebertialmeida** [comment]
Can you provide more details, how to reproduce and the error?

**Comment by mitulmarsonia** [comment]
![screenshot 2017-04-08 23 51 28](https://cloud.githubusercontent.com/assets/10178632/24831403/6da74238-1cb6-11e7-877c-8522e4501532.png)
Getting version error.
