### ISSUE TITLE
Module compiled with Swift 3.0.1

### ISSUE THREAD

**Issue by Skyna** [FolioReader/FolioReaderKit#172]
Greetings,

I use CocoaPods for the integration of this library. However, sinds recently when i updated my Xcode to 8.1. I am getting this issue from within my project:

"Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1"

So my question is. When will there be a release of this library which is compiled in Swift 3.0.1?

Thanks!

**Comment by perlmunger** [comment]
I'm getting the same error, but when building with Carthage

**Comment by perlmunger** [comment]
This worked for me using carthage:

`carthage update --platform iOS --no-use-binaries`

**Comment by hebertialmeida** [comment]
Does it solve the problem? I will close the issue, feel free to open again if not solved.
