### ISSUE TITLE
Bug at scroll to next chapter in horizontal mode

### ISSUE THREAD

**Issue by tiana890** [FolioReader/FolioReaderKit#173]
Strange situation sometimes occurs when I scroll the book between tho chapters. The next chapter appears on its last page, not on the first one as it must be. Perhaps you can help with this situation?  It happens with horizontal scroll mode.

**Comment by tiana890** [comment]
I suppose the problem is in FolioReaderPage.swift:
    // MARK: - UIWebView Delegate
    
    open func webViewDidFinishLoad(_ webView: UIWebView) {
		//...
        
        let direction: ScrollDirection = FolioReader.needsRTLChange ? .positive() : .negative()
        
        if pageScrollDirection == direction && isScrolling && readerConfig.scrollDirection != .horizontalWithVerticalContent {
            scrollPageToBottom()
        }
        
       //...
    }
It seems to me that sometimes scrollToBottom() calls when it is not needed to be called.

**Comment by tiana890** [comment]
I figured out what is the problem. It is in FolioReaderCenter.swift file:

    //....
    open func scrollViewDidScroll(_ scrollView: UIScrollView) {
        //......
            pageScrollDirection = scrollView.contentOffset.forDirection() < pointNow.forDirection() ? .negative() : .positive()
    }
The property pageScrollDirection changes many times here. So (according to my previous comment) when the pageScrollDirection in webViewDidFinishLoad() method is calculated the global property pageScrollDirection can be different. By the way the property pointNow is the point in one UIScrollView, but the delegate scrollViewDidScroll is called for all UIScrollViews (there is no checking). SO it looks a bit messy too.

**Comment by hebertialmeida** [comment]
Did you fixed?

**Comment by tiana890** [comment]
I fixed the problem in my project. But it looks more like temporary solution. I can show it if you need. What should I do?

**Comment by PravinNagargoje** [comment]
In  FolioReaderPage.swift file.
I think you don't need **isScrolling**  condition. If you remove it, it will never go to the last page in horizontal scrolling.
`open func webViewDidFinishLoad(_ webView: UIWebView) {
    //...

    let direction: ScrollDirection = FolioReader.needsRTLChange ? .positive() : .negative()

    if pageScrollDirection == direction && isScrolling && readerConfig.scrollDirection != .horizontalWithVerticalContent {
        scrollPageToBottom()
    }

   //...
}`
