### ISSUE TITLE
Pod version conflict with Realm swift

### ISSUE THREAD

**Issue by lukacs-m** [FolioReader/FolioReaderKit#175]
Hello,
First I wanted to thank you for the great work your are doing.
I just wanted to let you know that FolioReader generates a Pod conflict with the new realm swift.
Indeed realm swift had a new version v2.x out recently and It seems that FolioReader is still using an old version of realm swift v1.x.
This situation seems to generate a conflict between Reamlswift and FolioReader when pod install is called.
Trying to revert to realm v1.x in my project seems counter intuitive and generates file format conflicts.
I wonder if there is a simple solution to this problem other than reverting to a previous version of realm swift.
Thank you in advance for any tips.

**Comment by revolter** [comment]
Are you receiving any errors in terminal? Because I'm using Realm Swift too but I don't get any when I install the pods, though Xcode can't find the `FolioReaderKit` module.

**Comment by payalbaldota** [comment]
Any updates on this? I am also getting the error for many dependent frameworks for still using Swift 2.3. My OS version is 10.11.6. I am trying to build the Example on Xcode 8.0

**Comment by hebertialmeida** [comment]
I am not able to maintain Swift 2.3, new fixes and features will follow master with Swift 3+.

Sorry...
