### ISSUE TITLE
Class PLBuildVersion is implemented in both

### ISSUE THREAD

**Issue by aleksandrkr-hyuna** [FolioReader/FolioReaderKit#180]
Hi!
I have a problem:
Warning in log
objc[4731]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x118b4d998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x118972d38). One of the two will be used. Which one is undefined.

how i can close access to PhotoLibraryServices? 
I do not want to share information in book, and i using "config.allowSharing = false", but i cant stop this warning, because folio reader try to access camera in delegate, when i run my project. 

Please help me)

**Comment by hebertialmeida** [comment]
What is the problem with this warning?

**Comment by hebertialmeida** [comment]
Closed due to inactivity.
