### ISSUE TITLE
Access ePub metadata

### ISSUE THREAD

**Issue by revolter** [FolioReader/FolioReaderKit#182]
How can one access an ePub's metadata (title, cover, etc)? I managed to do it using `FRMetadata` after marking it as `public`. Is there another way? If not, why is it (and `FRBook`, `FREpubParser`, `readEpub` too) private?

**Comment by hebertialmeida** [comment]
Hey, in the beginning everything was private, I have changed it and trying to open the most of things. You can expose it if you with, and please make a PR 😄

**Comment by revolter** [comment]
Well, I previously decided to go with my own fork with public APIs but if you can be active and review my PRs, I'll surely create some 😄

**Comment by hebertialmeida** [comment]
I can definitely review it, as it is my side project I don't have full time for it.. I do my best, that is why I need people like you 👍

**Comment by revolter** [comment]
I plan to use this library extensively in an app so I'll want some fixes for myself too.

**Comment by hebertialmeida** [comment]
@revolter Have you implemented that or the latest version provides what do you need?

**Comment by revolter** [comment]
Wow, the many GitHub notifications I receive hid this, so, currently I don't need this anymore, and the metadata can be accessed using [these methods](https://github.com/FolioReader/FolioReaderKit/blob/71c9b59631f4a7bd05d18f2950d1fa2084ab0f44/Source/FolioReaderKit.swift#L312-L333).

**Comment by hebertialmeida** [comment]
Alright!
