### ISSUE TITLE
Bug with open FolioReader from the controller with keyboard

### ISSUE THREAD

**Issue by tiana890** [FolioReader/FolioReaderKit#187]
Hello! Perhaps, u can help me. I have a collection in my UIViewController and UISearchBar above it. 
When the keyboard is shown and I tap the cell on my collection I go to another controller and present FolioReader there. Sometimes (not every time) I get strange crash. 
I have already opened the issue with UISearchBar (https://github.com/FolioReader/FolioReaderKit/issues/163). 
This is the log:

#0. Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1ce34586 objc_msgSend + 5
1  UIKit                          0x22e31411 -[_UIWebViewScrollViewDelegateForwarder forwardInvocation:] + 140
2  CoreFoundation                 0x1dbca42b ___forwarding___ + 350
3  CoreFoundation                 0x1daeff08 _CF_forwarding_prep_0 + 24
4  UIKit                          0x22c67c95 -[UIScrollView _getDelegateZoomView] + 96
5  UIKit                          0x22c67b59 -[UIScrollView _zoomScaleFromPresentationLayer:] + 40
6  UIKit                          0x22c67b0d -[UIWebDocumentView _zoomedDocumentScale] + 60
7  UIKit                          0x22c676c5 -[UIWebDocumentView _layoutRectForFixedPositionObjects] + 104
8  UIKit                          0x22c67517 -[UIWebDocumentView _updateFixedPositionedObjectsLayoutRectUsingWebThread:synchronize:] + 46
9  UIKit                          0x22c699b5 -[UIWebDocumentView _updateFixedPositioningObjectsLayoutAfterScroll] + 26
10 UIKit                          0x22c6998f -[UIWebBrowserView _updateFixedPositioningObjectsLayoutAfterScroll] + 56
11 CoreFoundation                 0x1db72761 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 10
12 CoreFoundation                 0x1db7209d _CFXRegistrationPost + 386
13 CoreFoundation                 0x1db71e81 ___CFXNotificationPost_block_invoke + 40
14 CoreFoundation                 0x1dbcd81d -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1188
15 CoreFoundation                 0x1dad209d _CFXNotificationPost + 540
16 Foundation                     0x1e3fc6b3 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
17 UIKit                          0x23581f19 -[UIInputWindowController postEndNotifications:withInfo:] + 584
18 UIKit                          0x23584403 __77-[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:]_block_invoke_2.941 + 94
19 UIKit                          0x2357f6df -[UIInputWindowController performWithSafeTransitionFrames:] + 170
20 UIKit                          0x23584291 __77-[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:]_block_invoke.932 + 504
21 UIKit                          0x22c51d5b -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 440
22 UIKit                          0x22c51829 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 214
23 UIKit                          0x22c516d9 -[UIViewAnimationState animationDidStop:finished:] + 128
24 QuartzCore                     0x20a37a77 CA::Layer::run_animation_callbacks(void*) + 252
25 libdispatch.dylib              0x1d26d083 _dispatch_client_callout + 22
26 libdispatch.dylib              0x1d2715fd _dispatch_main_queue_callback_4CF + 890
27 CoreFoundation                 0x1db82a17 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
28 CoreFoundation                 0x1db80cff __CFRunLoopRun + 1422
29 CoreFoundation                 0x1dad0073 CFRunLoopRunSpecific + 486
30 CoreFoundation                 0x1dacfe81 CFRunLoopRunInMode + 104
31 GraphicsServices               0x1f27cbfd GSEventRunModal + 156
32 UIKit                          0x22c8482f -[UIApplication _run] + 574
33 UIKit                          0x22c7ef61 UIApplicationMain + 150
34 Bookscriptor                   0x24be4 main (AppDelegate.swift:17)
35 libdispatch.dylib              0x1d29a50b (Missing)

--

#0. Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x1ce34586 objc_msgSend + 5
1  UIKit                          0x22e31411 -[_UIWebViewScrollViewDelegateForwarder forwardInvocation:] + 140
2  CoreFoundation                 0x1dbca42b ___forwarding___ + 350
3  CoreFoundation                 0x1daeff08 _CF_forwarding_prep_0 + 24
4  UIKit                          0x22c67c95 -[UIScrollView _getDelegateZoomView] + 96
5  UIKit                          0x22c67b59 -[UIScrollView _zoomScaleFromPresentationLayer:] + 40
6  UIKit                          0x22c67b0d -[UIWebDocumentView _zoomedDocumentScale] + 60
7  UIKit                          0x22c676c5 -[UIWebDocumentView _layoutRectForFixedPositionObjects] + 104
8  UIKit                          0x22c67517 -[UIWebDocumentView _updateFixedPositionedObjectsLayoutRectUsingWebThread:synchronize:] + 46
9  UIKit                          0x22c699b5 -[UIWebDocumentView _updateFixedPositioningObjectsLayoutAfterScroll] + 26
10 UIKit                          0x22c6998f -[UIWebBrowserView _updateFixedPositioningObjectsLayoutAfterScroll] + 56
11 CoreFoundation                 0x1db72761 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 10
12 CoreFoundation                 0x1db7209d _CFXRegistrationPost + 386
13 CoreFoundation                 0x1db71e81 ___CFXNotificationPost_block_invoke + 40
14 CoreFoundation                 0x1dbcd81d -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1188
15 CoreFoundation                 0x1dad209d _CFXNotificationPost + 540
16 Foundation                     0x1e3fc6b3 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
17 UIKit                          0x23581f19 -[UIInputWindowController postEndNotifications:withInfo:] + 584
18 UIKit                          0x23584403 __77-[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:]_block_invoke_2.941 + 94
19 UIKit                          0x2357f6df -[UIInputWindowController performWithSafeTransitionFrames:] + 170
20 UIKit                          0x23584291 __77-[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:]_block_invoke.932 + 504
21 UIKit                          0x22c51d5b -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 440
22 UIKit                          0x22c51829 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 214
23 UIKit                          0x22c516d9 -[UIViewAnimationState animationDidStop:finished:] + 128
24 QuartzCore                     0x20a37a77 CA::Layer::run_animation_callbacks(void*) + 252
25 libdispatch.dylib              0x1d26d083 _dispatch_client_callout + 22
26 libdispatch.dylib              0x1d2715fd _dispatch_main_queue_callback_4CF + 890
27 CoreFoundation                 0x1db82a17 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
28 CoreFoundation                 0x1db80cff __CFRunLoopRun + 1422
29 CoreFoundation                 0x1dad0073 CFRunLoopRunSpecific + 486
30 CoreFoundation                 0x1dacfe81 CFRunLoopRunInMode + 104
31 GraphicsServices               0x1f27cbfd GSEventRunModal + 156
32 UIKit                          0x22c8482f -[UIApplication _run] + 574
33 UIKit                          0x22c7ef61 UIApplicationMain + 150
34 Bookscriptor                   0x24be4 main (AppDelegate.swift:17)
35 libdispatch.dylib              0x1d29a50b (Missing)

#1. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1d35a83c mach_msg_trap + 20
1  libsystem_kernel.dylib         0x1d35a62f mach_msg + 42
2  CoreFoundation                 0x1db82869 __CFRunLoopServiceMachPort + 136
3  CoreFoundation                 0x1db80b67 __CFRunLoopRun + 1014
4  CoreFoundation                 0x1dad0073 CFRunLoopRunSpecific + 486
5  CoreFoundation                 0x1dacfe81 CFRunLoopRunInMode + 104
6  Foundation                     0x1e4020db -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 260
7  Foundation                     0x1e420df1 -[NSRunLoop(NSRunLoop) runUntilDate:] + 86
8  UIKit                          0x2358ccb3 -[UIEventFetcher threadMain] + 128
9  Foundation                     0x1e4eb0d1 __NSThread__start__ + 1160
10 libsystem_pthread.dylib        0x1d424a17 _pthread_body + 216
11 libsystem_pthread.dylib        0x1d42493d _pthread_start + 234
12 libsystem_pthread.dylib        0x1d422498 thread_start + 8

#2. com.twitter.crashlytics.ios.MachExceptionServer
0  Bookscriptor                   0x1642c5 CLSProcessRecordAllThreads + 1913541
1  Bookscriptor                   0x1642c5 CLSProcessRecordAllThreads + 1913541
2  Bookscriptor                   0x1641bd CLSProcessRecordAllThreads + 1913277
3  Bookscriptor                   0x15868f CLSHandler + 1865359
4  Bookscriptor                   0x1542fb CLSMachExceptionServer + 1848059
5  libsystem_pthread.dylib        0x1d424a17 _pthread_body + 216
6  libsystem_pthread.dylib        0x1d42493d _pthread_start + 234
7  libsystem_pthread.dylib        0x1d422498 thread_start + 8

#3. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1d35a83c mach_msg_trap + 20
1  libsystem_kernel.dylib         0x1d35a62f mach_msg + 42
2  CoreFoundation                 0x1db82869 __CFRunLoopServiceMachPort + 136
3  CoreFoundation                 0x1db80b67 __CFRunLoopRun + 1014
4  CoreFoundation                 0x1dad0073 CFRunLoopRunSpecific + 486
5  CoreFoundation                 0x1dacfe81 CFRunLoopRunInMode + 104
6  CFNetwork                      0x1e19adb9 +[NSURLConnection(Loader) _resourceLoadLoop:] + 416
7  Foundation                     0x1e4eb0d1 __NSThread__start__ + 1160
8  libsystem_pthread.dylib        0x1d424a17 _pthread_body + 216
9  libsystem_pthread.dylib        0x1d42493d _pthread_start + 234
10 libsystem_pthread.dylib        0x1d422498 thread_start + 8

#4. Thread
0  libsystem_kernel.dylib         0x1d36f810 __psynch_cvwait + 24
1  libsystem_pthread.dylib        0x1d423d0f _pthread_cond_wait + 542
2  libsystem_pthread.dylib        0x1d4250af pthread_cond_wait + 38
3  libc++.1.dylib                 0x1cdbc37f std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 118
4  JavaScriptCore                 0x219cd86f void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 88
5  JavaScriptCore                 0x219cd7f3 bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 154
6  JavaScriptCore                 0x219cd6fb std::__1::__shared_ptr_emplace<std::__1::mutex, std::__1::allocator<std::__1::mutex> >::~__shared_ptr_emplace() + 8
7  libswiftos.dylib               0x17670450 (Missing)
8  libsystem_pthread.dylib        0x1d424a17 _pthread_body + 216
9  libsystem_pthread.dylib        0x1d42493d _pthread_start + 234
10 libsystem_pthread.dylib        0x1d422498 thread_start + 8

#5. WebThread
0  libsystem_kernel.dylib         0x1d35a83c mach_msg_trap + 20
1  libsystem_kernel.dylib         0x1d35a62f mach_msg + 42
2  CoreFoundation                 0x1db82869 __CFRunLoopServiceMachPort + 136
3  CoreFoundation                 0x1db80b67 __CFRunLoopRun + 1014
4  CoreFoundation                 0x1dad0073 CFRunLoopRunSpecific + 486
5  CoreFoundation                 0x1dacfe81 CFRunLoopRunInMode + 104
6  WebCore                        0x21c671b3 RunWebThread(void*) + 426
7  libsystem_pthread.dylib        0x1d424a17 _pthread_body + 216
8  libsystem_pthread.dylib        0x1d42493d _pthread_start + 234
9  libsystem_pthread.dylib        0x1d422498 thread_start + 8

#6. JIT Worklist Worker Thread
0  libsystem_kernel.dylib         0x1d36f810 __psynch_cvwait + 24
1  libsystem_pthread.dylib        0x1d423d0f _pthread_cond_wait + 542
2  libsystem_pthread.dylib        0x1d4250af pthread_cond_wait + 38
3  libc++.1.dylib                 0x1cdbc37f std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 118
4  JavaScriptCore                 0x219bb825 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1ll, 1000000000ll> > >) + 1700
5  JavaScriptCore                 0x21845861 JSC::JITWorklist::runThread() + 192
6  JavaScriptCore                 0x21845bed WTF::Vector<WTF::RefPtr<JSC::JITWorklist::Plan>, 32ul, WTF::CrashOnOverflow, 16ul>::expandCapacity(unsigned long, WTF::RefPtr<JSC::JITWorklist::Plan>*) + 10
7  libcoretls_cfhelpers.dylib     0x36c7a8a0 (Missing)
8  JavaScriptCore                 0x2150f3cb WTF::wtfThreadEntryPoint(void*) + 12
9  libsystem_pthread.dylib        0x1d424a17 _pthread_body + 216
10 libsystem_pthread.dylib        0x1d42493d _pthread_start + 234
11 libsystem_pthread.dylib        0x1d422498 thread_start + 8

#7. WTF Parallel Helper Thread
0  libsystem_kernel.dylib         0x1d36f810 __psynch_cvwait + 24
1  libsystem_pthread.dylib        0x1d423d0f _pthread_cond_wait + 542
2  libsystem_pthread.dylib        0x1d4250af pthread_cond_wait + 38
3  libc++.1.dylib                 0x1cdbc37f std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 118
4  JavaScriptCore                 0x219bb825 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1ll, 1000000000ll> > >) + 1700
5  JavaScriptCore                 0x219bb01b WTF::ParallelHelperPool::waitForClientWithTask(WTF::Locker<WTF::LockBase> const&) + 352
6  JavaScriptCore                 0x219badab WTF::ParallelHelperPool::helperThreadBody() + 62
7  JavaScriptCore                 0x2150f46d WTF::threadEntryPoint(void*) + 146
8  JavaScriptCore                 0x2150f3cb WTF::wtfThreadEntryPoint(void*) + 12
9  libsystem_pthread.dylib        0x1d424a17 _pthread_body + 216
10 libsystem_pthread.dylib        0x1d42493d _pthread_start + 234
11 libsystem_pthread.dylib        0x1d422498 thread_start + 8

#8. Thread
0  libsystem_kernel.dylib         0x1d370744 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1d4229a1 _pthread_wqthread + 1274
2  libsystem_pthread.dylib        0x1d42248c start_wqthread + 8

#9. Thread
0  libsystem_kernel.dylib         0x1d370744 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1d4229a1 _pthread_wqthread + 1274
2  libsystem_pthread.dylib        0x1d42248c start_wqthread + 8

#10. Thread
0  libsystem_kernel.dylib         0x1d370744 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1d4227fd _pthread_wqthread + 854
2  libsystem_pthread.dylib        0x1d42248c start_wqthread + 8

#11. Thread
0  libsystem_kernel.dylib         0x1d370744 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1d4229a1 _pthread_wqthread + 1274
2  libsystem_pthread.dylib        0x1d42248c start_wqthread + 8

**Comment by tiana890** [comment]
One more thing. After investigating the issue I found that it happens when FolioReaderWebView is not deallocated. The state of allocations after this crash:
![image](https://cloud.githubusercontent.com/assets/2170659/21006621/84861cd2-bd5b-11e6-9765-a45fc28f1485.png)

**Comment by tiana890** [comment]
I found that the problem is caused because of this line of code in FolioReaderCenter:

     open func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath)     -> UICollectionViewCell {
        //...
        cell.webView.scrollView.delegate = self
        //....

In order to fix this situation it is better to set this delegate to nil in deinit of FolioReaderPage.swift:

deinit {
        webView.scrollView.delegate = nil
        //.....
    }

**Comment by hebertialmeida** [comment]
Hey @tiana890, does it fixes you bug? Could you please make a PR?

**Comment by tiana890** [comment]
@hebertialmeida yes it fixed my issue.

**Comment by hebertialmeida** [comment]
Hey, it is a Pull Request.

**Comment by hebertialmeida** [comment]
I think this can be closed by the PR #194
