### ISSUE TITLE
Not Sure How To Use Font Blaster

### ISSUE THREAD

**Issue by perlmunger** [FolioReader/FolioReaderKit#192]
I need to add a font to my project. If I just add the font to my bundle making sure it's part of the build target, is that enough for Font Blaster to pick it up, or do I need to do something else? Thanks.

**Comment by perlmunger** [comment]
Maybe I have the wrong expectation here. Does this library support using the fonts specified by the ePub?

**Comment by hebertialmeida** [comment]
Hey, currently the app override the book fonts, because it focus o end User Experience, as the books comes from many publishers each book has one font style and size pattern. 

Although, we want to support the default book font in future.
