### ISSUE TITLE
Working with epub created with iBooks Author app

### ISSUE THREAD

**Issue by uituit** [FolioReader/FolioReaderKit#193]
Just tried to use the Kit to load a epub book I made in iBooks Author app, but crashes because there's no Cover image. Wondering if the epub created by Apple's epub solution is not in a common structure when comparing with epub generated by, i.e. Calibri.

**Comment by hebertialmeida** [comment]
The format generated by iBooks Author is a totally different format, not the same standards from ePub 2 and ePub 3. There is not support for that.
