### ISSUE TITLE
Question about Javascript function.

### ISSUE THREAD

**Issue by alexliubj** [FolioReader/FolioReaderKit#195]
I saw a function in javascript file. `function setMediaOverlayStyleColors(color, colorHighlight)`
What exactly this one is doing?
Just overwrite css above the CSS comes with EPUB books?

Thanks,

**Comment by hebertialmeida** [comment]
This function is to set media overlay style color :)

It do not override the CSS from book, but when you are playing the book with TTS or Media Overlay this set the selected text color.
