### ISSUE TITLE
How to make page size larger?

### ISSUE THREAD

**Issue by piechart** [FolioReader/FolioReaderKit#197]
I've tried to dance with webViewFrame() but nothing finished with result I'm waiting for.

Hot to resize it to real device size? Also pinch-to-zoom would be useful.

![2016-12-20 23 58 54](https://cloud.githubusercontent.com/assets/17230738/21367739/53a42050-c710-11e6-88ba-379ed6d7d792.png)
![2016-12-20 23 59 05](https://cloud.githubusercontent.com/assets/17230738/21367738/53a37614-c710-11e6-8745-dc8eb01217b6.png)

**Comment by hebertialmeida** [comment]
This page is probably a bitmap image, that is why the size is like that.

**Comment by HadrienGardeur** [comment]
Certainly looks like a bitmap to me, this might be a fixed layout EPUB.

**Comment by sam961** [comment]
for zoom try to add this into folioreaderpage 👍 
webview.scalesPageToFit=YES

**Comment by hebertialmeida** [comment]
Closed due to inactivity.
