### ISSUE TITLE
Crash FolioReader after edit UITextField

### ISSUE THREAD

**Issue by isakvan** [FolioReader/FolioReaderKit#199]
Thank you for a wonderful library!
Unfortunately I faced with the library crash. 
This occurs if the application have UITextField. After calling FolioReader, close it and  try to edit UITextField and close keyboard(finish edit UITextField), at this time causes crash the application and  I have zombies message - 

![image](https://cloud.githubusercontent.com/assets/1402101/21580613/0b96f4c6-d00d-11e6-83e0-404fd28e0258.png)

I created project that present it to you
https://1drv.ms/u/s!ApGEg5XDO9LzgTEaRfR0LFUxn38_ (put it to your browser by copy-paste)

Maybe it happened after - 
https://github.com/FolioReader/FolioReaderKit/issues/187

Thanks a lot

**Comment by isakvan** [comment]
I downloaded the code library FolioReader and connect locally
  pod 'FolioReaderKit',: path => '~ / FolioReaderkit
**crash not occurs**

possible correction has not yet entered the pod release?

**Comment by hebertialmeida** [comment]
I think it is already fixed, I am releasing a new version now...
