### ISSUE TITLE
Add option to delete or keep original book.epub

### ISSUE THREAD

**Issue by hebertialmeida** [FolioReader/FolioReaderKit#20]
Today the original epub is always removed, add a option to keep the original.

**Comment by kjantzer** [comment]
I'm curious, what do you mean its "removed"?

**Comment by hebertialmeida** [comment]
The original zipped epub file is replaced by a folder with the same name, unzipped. Seems that it is the same but it's not, this is to avoid unzip files everytime.

**Comment by hebertialmeida** [comment]
Done.

Use `shouldRemoveEpub: false` in init.

> FolioReader.presentReader(parentViewController: self, withEpubPath: bookPath!, andConfig: config, shouldRemoveEpub: false)

**Comment by revolter** [comment]
Is there any option to change the default location of the unzipped ePubs? I would like to keep them in a subfolder.

**Comment by hebertialmeida** [comment]
@revolter We don't have that, but I think it is interesting to have..

**Comment by revolter** [comment]
Can you give me a direction of where I'd be done? I might open a PR.

**Comment by hebertialmeida** [comment]
Basically you can add an extra parameter to keep the original book at some path, when unzip the book you can move that to this informed path.

**Comment by revolter** [comment]
I was meaning to ask about a/some specific classes, as I'm not accustomed to the project yet.
