### ISSUE TITLE
Excuse me, how can I  make it support iOS 7?

### ISSUE THREAD

**Issue by CeeYang** [FolioReader/FolioReaderKit#201]
Thanks for noting.
    I had browsed the epub demo in github which write with Objective-C,it not very well. 
    Is there any way to make this project support iOS 7, and I want use it in Objective-C.
    Any suggest？ 
    Thanks.

**Comment by hebertialmeida** [comment]
As the code is written in Swift 3 you will probably have many difficult with that, but may be possible.. http://stackoverflow.com/questions/38414469/do-xcode-8-swift-3-apps-run-on-ios-7-successfully
