### ISSUE TITLE
Arabic horizontal Direction

### ISSUE THREAD

**Issue by sam961** [FolioReader/FolioReaderKit#202]
Guys, 
The horizontal scroll for books is buggy, who can work with me to fix this issue  especially for arabic books ?

**Comment by sam961** [comment]
CGAffineTransform is doing the job.
But when reading the end of the webview...It is not moving to the next chapter....
What could be the problem ?

**Comment by hebertialmeida** [comment]
This is a really good question, I tested couple books and seems that some work, and others not.

As I don't understand RTL languages is very hard to even test it 😄

**Comment by hebertialmeida** [comment]
We may can discuss it on Slack, there are some guys that understand a lot of ePub. I have asked you on gitter for an email, so I can invite you.

**Comment by sam961** [comment]
Hehe, iam working on it and It must be solved...it is not related to arabic books anymore.
I put the same function for english books, and when it reached the end of the webview it stucks.
Ok i will be ready for an invite

**Comment by revolter** [comment]
Isn't this a duplicate of #124?

**Comment by hebertialmeida** [comment]
@revolter It is.
