### ISSUE TITLE
Objective-C Example Please

### ISSUE THREAD

**Issue by harishsave** [FolioReader/FolioReaderKit#203]
I have a project in Objective-C and I want to use FolioReaderKit in it. I've added the frameworks via Carthage. Can anyone please explain me how to open the epub file in the reader and show it, using Objective-C?

**Comment by iamgooddeveloper** [comment]
I'm using CocoaPods

1) in Podfile: 
`pod 'FolioReaderKit', '~> 1.0.0'`

2) in ViewController: 
`@import FolioReaderKit; `

3) in function:
```
    NSString *filePath = [[NSBundle mainBundle] pathForResource:@"book" ofType:@"epub"];
    FolioReaderConfig *config = [[FolioReaderConfig alloc] init];
    [FolioReader presentReaderWithParentViewController:self withEpubPath: filePath andConfig:config shouldRemoveEpub:true animated:true];
```

**Comment by hebertialmeida** [comment]
Do you think you can make Pull Request with a sample?

**Comment by iamgooddeveloper** [comment]
@hebertialmeida Yes, I can

**Comment by harishsave** [comment]
@iamgooddeveloper Thanks. I'm now able to open the ebook. All the options are working, but when I click on 'Aa' icon then the app crashes. I'm attaching the screenshot.
![error](https://cloud.githubusercontent.com/assets/13299197/23024977/4a94c9ca-f482-11e6-8f49-fd4fb9108715.png)

**Comment by iamgooddeveloper** [comment]
@harishsave first of all what versions of Xcode and FolioReader you use?

**Comment by hebertialmeida** [comment]
@harishsave This crash is already fixed on latest master. @iamgooddeveloper Are you able to create a Objective-C and make a PR?

**Comment by nzrin** [comment]
```
NSString *filePath = [[NSBundle mainBundle] pathForResource:@"book" ofType:@"epub"];
    FolioReaderConfig *config = [[FolioReaderConfig alloc] init];
    [FolioReader presentReaderWithParentViewController:self withEpubPath: filePath andConfig:config shouldRemoveEpub:true animated:true];
```

I'm using this code for version 1.3.0. Unfortunately got this error : 

"No known class method for selecter 'presentReaderWithParentViewController....etc'

It is worked perfectly if I use version 1.0.0.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
