### ISSUE TITLE
Custom Font make crash

### ISSUE THREAD

**Issue by ghost** [FolioReader/FolioReaderKit#207]
FolioReaderKit Version is 1.1.0, if you use custom font, it will make a crash. The crash is that  array out of bound, I hope author could fix it, thanks.
```
func selectSegmentAtIndex(_ index: Int) {
        assert(index >= 0 && index < self.segments.count, "Index at \(index) is out of bounds")
        self.selectSegment(self.segments[index])
}
```
 
<img width="952" alt="qq20170121-102619 2x" src="https://cloud.githubusercontent.com/assets/10344959/22171245/bad1ea92-dfc4-11e6-96d5-f451d10d737c.png">

**Comment by JobsCrazy** [comment]
@hebertialmeida

**Comment by sam961** [comment]
did u added it to the css file too ?

**Comment by PravinNagargoje** [comment]
Tried by adding to css and js files also, still gets crash at the time of using font. Works only if added iOS fonts.

**Comment by iconmamobility** [comment]
i got below issue when i add custom font.

**fatal error: unexpectedly found nil while unwrapping an Optional value**

**Comment by hebertialmeida** [comment]
I plan to add custom font support in the future as a new feature, for now I will close this.
