### ISSUE TITLE
Add vertical scrubber to quickly jump pages in current chapter

### ISSUE THREAD

**Issue by kjantzer** [FolioReader/FolioReaderKit#21]
Here is what it looks like in iBooks (although I think the scrubber is too close to the text)

![photo jan 07 8 23 59 am](https://cloud.githubusercontent.com/assets/467487/12175680/72ae9d5a-b518-11e5-8ac4-57030938ab67.png)

**Comment by kjantzer** [comment]
@hebertialmeida Check it out.

![scubber mov](https://cloud.githubusercontent.com/assets/467487/12271889/51cfd2ea-b912-11e5-901a-cd8ed426da0f.gif)

I still need to working out the positioning on different devices (I've only tested on iphone 6)

**Comment by hebertialmeida** [comment]
Nice!

It scrolls the chapter position (UIScrollView) or it also change chapters (UICollectionView)?

**Comment by kjantzer** [comment]
Just the `UIScrollView` at the moment

**Comment by empedocle** [comment]
I too would like UICollectionView, for horizontal scroll as well, as a way to easily and quickly change sections, as well as having the scroller show the whole book. I've tried doing it before without much luck but if I start a possibly planned project and use FolioReaderKit, I'll see what I can figure out.

**Comment by hebertialmeida** [comment]
@empedocle Would be nice if you could help us on this implementation 👍
If you want to work on this you can open a new issue I think.

**Comment by empedocle** [comment]
I'm only a beginner Swift programmer but I'll try when I can. I had started something similar on OS X but haven't gotten too far with it yet. Will try when I get a chance.

**Comment by hebertialmeida** [comment]
Interesting, I really want to port this to macOS.

**Comment by empedocle** [comment]
Yes a macOS port would be great, perhaps with at the beginning, a simple library manager like iBooks. I used Realm since it was easier than learning CoreData, and my app so far just opens an external viewer like calibre. We have calibre for the desktop but a simple and elegant app to merely manage a library and view books for macOS, something similar to iBooks but with a bit more options for management, there's nothing out yet.

**Comment by hebertialmeida** [comment]
I have created a issue for this #89
