### ISSUE TITLE
Invert Selection Indicator

### ISSUE THREAD

**Issue by sam961** [FolioReader/FolioReaderKit#211]
![simulator screen shot feb 2 2017 10 42 55 am](https://cloud.githubusercontent.com/assets/4921874/22542472/99df43b0-e934-11e6-9f18-a859de90e3d1.png)

How to invert the start of the selection indicator from LTR to RTL.

The start of the text is from the right so the indicator should start from the right.

is it related to css or js or ios code ?

**Comment by hebertialmeida** [comment]
This selection is native from iOS, may have to inform the right direction to webView, so it can invert that, but I have never tried.

**Comment by hebertialmeida** [comment]
Closed due to inactivity.
