### ISSUE TITLE
Empty ePub file gets opened

### ISSUE THREAD

**Issue by payalbaldota** [FolioReader/FolioReaderKit#213]
@hebertialmeida 
[Wildlife%20Adventure.zip] (Could not upload epub file directly here) (https://github.com/FolioReader/FolioReaderKit/files/763249/Wildlife.20Adventure.zip) 
when we pass this file to FolioReader framework, empty file is displayed. We have validated the file successfully using the link you provided(validator - http://validator.idpf.org). Can you please check what is the issue with the file. Why FolioReaderKit famework is not able to display it? as per our debugging file gets parsed correctly.

**Comment by PravinNagargoje** [comment]
We are able to open the book. I think issue is not in the file, I also validated the book. It's clean. Make sure you are using latest version of FolioReaderKit framework. I have attached below screenshot of book I was able to open.
![simulator screen shot 11-mar-2017 12 46 01 pm](https://cloud.githubusercontent.com/assets/17273000/23821476/95d295dc-0659-11e7-8632-f5c61c6dd932.png)
