### ISSUE TITLE
Loading 2 epubs at the same time for language learners

### ISSUE THREAD

**Issue by shinss61** [FolioReader/FolioReaderKit#214]
Thank you for your great work !

I'm not a developer. This project is very impressive !!

It'll be great if i can load 2 language epubs at the same time.
When i read English version epub, 
if i can change another language of similar page(based on % of chapter) with button, it might great.
Cause I'm not a native. So if possible it's excellent tool for language learner!

Thank you !

**Comment by hebertialmeida** [comment]
This is now possible, there is even a example for that. #237
