### ISSUE TITLE
0 Remaining pages

### ISSUE THREAD

**Issue by sejas** [FolioReader/FolioReaderKit#222]
Hi !
Do you know why I get 0 pages left ? Someone had the same issue?
It just happen sometimes, and when I change the chapter from the menu, then the app usually starts to show the right value.
https://www.youtube.com/watch?v=zkIqcguh-rM

Thank you !!!
Any help appreciated.

**Comment by PravinNagargoje** [comment]
Hey error is in FolioReaderCenter.swift 

`func pagesForCurrentPage(_ page: FolioReaderPage?) {
        guard let page = page else { return }

		let pageSize = isDirection(pageHeight, pageWidth)
		pageIndicatorView?.totalPages = Int(ceil(page.webView.scrollView.contentSize.forDirection()/pageSize!))

		let pageOffSet = isDirection(page.webView.scrollView.contentOffset.x, page.webView.scrollView.contentOffset.x, page.webView.scrollView.contentOffset.y)
		let webViewPage = pageForOffset(pageOffSet, pageHeight: pageSize!)
        pageIndicatorView?.currentPage = webViewPage
    }
`
At the time of changing chapters the pageOffset should be 0  but somtimes it doesn't become zero so sets currentPage equal to max pages available and so remainingPagesLeft becomes zero.

I figured out why it is happening but couldn't fix it.

**Comment by zkenes** [comment]
@PravinNagargoje Did you solve this issue?

**Comment by hebertialmeida** [comment]
Is it happening on latest master version?

**Comment by zkenes** [comment]
@hebertialmeida yes, it is.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
