### ISSUE TITLE
A white background at the bottom when set to horizontal scrolling 

### ISSUE THREAD

**Issue by ladmini** [FolioReader/FolioReaderKit#224]
Hi dear,
Thank you so much for bringing me such a good epub reader. I found a problem when integration it. There is a white background at the bottom in the last page of each chapter when I set to horizontal page mode. You can refer to the picture below

http://chuantu.biz/t5/53/1490613571x2890173854.png
http://chuantu.biz/t5/53/1490614022x2890173854.png

I haven't solved this problem for a whole day. Can you give me some advice?  Thanks again ！

**Comment by hebertialmeida** [comment]
This is kind of a hack solution because of o a bug on webView. If we do not use this it will be black...

**Comment by ladmini** [comment]
@hebertialmeida Yes, I understand your code. If we need to customize the theme, then we need to customize this color. Thank you very much

**Comment by hebertialmeida** [comment]
This is a awkward solution, but for now I don't have a better solution for this...
