### ISSUE TITLE
Problems with table rendering

### ISSUE THREAD

**Issue by pklarl** [FolioReader/FolioReaderKit#225]
Hi guys,

we have some problems with the rendering of some tables in our EPUBs: 
Screenshot: ![folioreadertable](https://cloud.githubusercontent.com/assets/26718597/24366238/c5b4b89a-1318-11e7-8e64-0f0a98a72d56.PNG)

Do you have any idea what this cause may be?

Thanks in advance!

**Comment by hebertialmeida** [comment]
Tables are a big problem on epub, even on readers like iBooks. I think you will have to play a little bit with the book css.

**Comment by pklarl** [comment]
The rendering in other readers such as iBooks (iOS), Icecream (Windows), Bookari (iOS and Andoid), and EPUBReader (Firefox Add-on) works well.

iBooks:
![ibookstable](https://cloud.githubusercontent.com/assets/26718597/24791033/e16418ca-1b78-11e7-95ea-7937b90a5897.png)

Bookari:
![bookaritable](https://cloud.githubusercontent.com/assets/26718597/24791013/ce876590-1b78-11e7-9d72-c58a4ba4cce4.png)

**Comment by pklarl** [comment]
We have found the error. In the CSS file of the FolioReader `word-break `is set to `break-word` in two places:

```
/ * allow breaking words on headers and anchors as they tend to larger font size or contain longer words * /
a, h1, h2, h3, h4, h5, h6 {
    word-break: break-word! important;
    -webkit-hyphens: none! important;
    hyphens: none! important;
}

body {
    word-break: break-word! important;
    -webkit-hyphens: auto! important;
    hyphens: auto! important;
}
```

As a result, especially in tables with non-uniform text distribution (for example, a lot of text in one column and little text in another column) in columns with little text, the words are partly wrapped between all the letters.

We were now able to correct the presentation of the tables via an additional entry in the CSS file of our EPUBs:

`table {word-break: normal;}`

Is it really necessary to set `word-break` to `break-word` in "body" as well?
Is it maybe necessary for any functions in FolioReader?

**Comment by pklarl** [comment]
It would be very helpful to get feedback on the described solution and answers to the two questions:
Is it really necessary to set word-break to break-word in "body" as well?
Is it maybe necessary for any functions in FolioReader?

**Comment by hebertialmeida** [comment]
To be honest with you I am not sure if it is necessary, but it definitely was in the past 😛. I did it years ago, and usually don't have to update it very often. I would go and use the fix that you did to specific.

What are your thoughts?

**Comment by pklarl** [comment]
I would prefer, it would be adapted in the CSS file from FolioReader ;)
But we can also maintain it separately or include it in our CCS files. Will monitor if any functions are affected and if necessary give feedback.

Thanks for your feedback.

**Comment by hebertialmeida** [comment]
Have you been using it for a while? If there is no problem could you make a small Pull request for that?

It is always better to include improvements in the source, so everyone can benefit from that.

**Comment by pklarl** [comment]
We have not been able to test much yet. But the first results looked good. Our iOS developer will contact you and make a small pull request.
We also have a few more problems (see my other Issus) and plan various extensions (iOS and Android). Here we would like to work closely with you.

**Comment by christian2denker** [comment]
Hi there, we created a pull request adding the line break mode for tables. It works fine for us.
