### ISSUE TITLE
Can't change UIWebView backgroundColor correctly when `paginationBreakingMode` is `.page` on night mode in iOS 10.3

### ISSUE THREAD

**Issue by Arcovv** [FolioReader/FolioReaderKit#227]
This bug happens in ios 10.3 or later. 😭

**Comment by hebertialmeida** [comment]
Hi @Arcovv could you give more details on how to simulate that?

**Comment by Arcovv** [comment]
Hi @hebertialmeida, it's can be simulated using the example book.

Open the `Sherlock Holmes A Scandal in Bohemia` book, change the `Day` mode to the `Night` mode. You see that javascript really change some text color by nightMode css file. But the background color of UIWebView still does not change.

This apperance when setting `paginationBreakingMode` to `.page` or using `css multiple columns` to split html screen. And this problem is happened upon iOS 10.3. Below 10.3, it worked fine. I think from iOS 10.3, the rendering mode of UIWebView had been changed.

**Comment by ladmini** [comment]
Same. Any update?

**Comment by hebertialmeida** [comment]
The fix is on master, I have other fixes to do, but please try that.
