### ISSUE TITLE
Simple way to get book html?

### ISSUE THREAD

**Issue by phalladar** [FolioReader/FolioReaderKit#229]
This library looks great in terms of a full-screen drop-in ePub reader but I'm wondering if there's a simple way for me to just grab the book html. I've spent some time poking through the code and I haven't been able to successfully do that yet. 

Any advice would be appreciated.

**Comment by tschob** [comment]
Hi @phalladar, do you just want to get html content or just display the book without the extra stuff (navigation bar, menu etc.)?

**Comment by phalladar** [comment]
Hey @tschob, I would like to have 100% control over the presentation of the textual book content. So ideally there would be a way for me to just grab the text (or HTML)

**Comment by tschob** [comment]
@phalladar  Maybe this fits your needs:

`FolioReaderCenterDelegate` calls the method `htmlContentForPage(_ page: FolioReaderPage, htmlContent: String) -> String` before the html is shown. The function contains the html which FolioReader created as parameter. The return String will replace the html inside the FolioReader.

Example:

```
FolioReader.shared.readerCenter?.delegate = self
```

```
func htmlContentForPage(_ page: FolioReaderPage, htmlContent: String) -> String {
	// Insert the Java Script bridge
	let modifiedHtmlContent = type(of: self).htmlContentWithInsertedJavaScriptBridge(from: htmlContent)
	return modifiedHtmlContent
}

**Comment by phalladar** [comment]
Kind of odd but for some reason even after setting the delegate `htmlContentForPage` isn't getting called.

That aside, it seems like in order to trigger it I will have to call `presentReader`, no? I would really like to not present the UI at all and just grab the text.

**Comment by hebertialmeida** [comment]
We maybe can include this as a feature, to read the epub and get the html without UI, should not be that hard.

Would this be usefull?

**Comment by phalladar** [comment]
I think it would be a much more generally useful library if you exposed that.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
