### ISSUE TITLE
epub responsive layout support

### ISSUE THREAD

**Issue by zuil7** [FolioReader/FolioReaderKit#230]
Hi,

Great app you have here. Just wanted to ask if this supports responsive layout for epub. I created a epub using this app https://www.pubcoder.com/ . Just notice that it is not responsive. The alignment of the images is a bit off. Is there something i need to set to make it responsive depending on the ios device?

Thanks!

**Comment by hebertialmeida** [comment]
FolioreaderKit does not support fixed layout epubs, only regular ones, you can use CSS media queries to show different things depending on the screen size.
