### ISSUE TITLE
Why my NightMode cant change BGColor

### ISSUE THREAD

**Issue by SuperZico** [FolioReader/FolioReaderKit#231]
![img_0516](https://cloud.githubusercontent.com/assets/13212385/24945132/ac418828-1f90-11e7-9ab0-880c758ea2b6.PNG)

**Comment by Julyyq** [comment]
@SuperZico There's a bug to set night mode. You could modify style.css file to change colors in night mode. See [example](https://github.com/Julyyq/FolioReaderKit/commit/8fc53a593529c9ae8dd9b368e3af663bd5d56e22) .

**Comment by SuperZico** [comment]
@Julyyq thx~~~it help me a lot~~

**Comment by GodYuanWang** [comment]
@Julyyq look like it doesn't work

**Comment by Julyyq** [comment]
@GodYuanWang It works definitely. 💯

**Comment by umarchohan** [comment]
@Julyyq can you share your style.css file with me ?

**Comment by hebertialmeida** [comment]
The fix is on master, I have other fixes to do, but please try that.
