### ISSUE TITLE
Empty page after Cover Image

### ISSUE THREAD

**Issue by Xopoko** [FolioReader/FolioReaderKit#232]
In the horizontal scrolling, in each book, after the Cover Image, the next page is just empty. In the vertical there is no such problem. Is there a solution for this? In Example project i see same bug.

**Comment by hebertialmeida** [comment]
This is a problem with webview pagination, I don't think there is something we can do.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
