### ISSUE TITLE
page/chapter change bug

### ISSUE THREAD

**Issue by GodYuanWang** [FolioReader/FolioReaderKit#233]
![bug](https://cloud.githubusercontent.com/assets/17892174/25168687/13b6c3c0-2517-11e7-9772-81419ca70eca.gif)![bug](https://cloud.githubusercontent.com/assets/17892174/25169378/604ba276-2519-11e7-9662-86d4549626d7.gif)

@hebertialmeida  What's happen with that? And in **.horizontal direction** the **nightMode** doesn't work.

**Comment by hebertialmeida** [comment]
This is a known bug for a long time, but there is no solution that I know yet. because there are two scrollviews and sometimes they conflict the direction, that is why it happens.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
