### ISSUE TITLE
EPub with audio: Audio keeps on looping 

### ISSUE THREAD

**Issue by zuil7** [FolioReader/FolioReaderKit#236]
Hi 
i have created a epub with audio read aloud. On the first page the audio is playing well but when the page changes the audio on the first page keeps on looping. I added also a audio file for read aloud on every page. It Should play the audio file on every page. Is there anything i can change to play the right audio i attached to every page? hoping for your response.

Thanks!

**Comment by kjantzer** [comment]
Are you using a properly formatted media overlay?

**Comment by hebertialmeida** [comment]
Still having this problem?

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
