### ISSUE TITLE
Core text replace WebView

### ISSUE THREAD

**Issue by returnight** [FolioReader/FolioReaderKit#245]
Do you have any plan to use Core text to replace WebView for FolioReader?

**Comment by hebertialmeida** [comment]
No plans, ePub rely on HTML and a lot of CSS, not that simple to solve the CSS dynamic styling part, no plans for that. Maybe in the future I would change the UIWebView for WKWebView.

**Comment by TyroneZhang** [comment]
I've changed the UIWebView for WKWebView,it was faster than UIWebView.

**Comment by hebertialmeida** [comment]
@tyroneZhang cold you make a pull request? Do you have it working?

**Comment by TyroneZhang** [comment]
I didn't implement the  WKWebView in the original FolioReaderKit project,
but in my project.
I'm willing to implement the WKWebView in FoliaReaderKit In the near future.
