### ISSUE TITLE
Problem with missing declarations 

### ISSUE THREAD

**Issue by thomers** [FolioReader/FolioReaderKit#247]
I'm using FolioReaderKit in an ObjC project, integrated as Cocoapod.

When I try to import the Swift-bridge header

`#import <FolioReaderKit/FolioReaderKit-Swift.h>`

I cannot compile due to these errors:

```
Cannot find protocol declaration for 'AVAudioPlayerDelegate' - FolioReaderKit-Swift.h
Cannot find protocol declaration for 'AVSpeechSynthesizerDelegate' - FolioReaderKit-Swift.h
Cannot find interface declaration for 'RealmSwiftObject' - FolioReaderKit-Swift.h
```

`@import FolioReaderKit;` does not work - `Use of '@import' when modules are disabled`
And Cocoapods forces me to use `use_frameworks!`

Any ideas how to fix this?

**Comment by thomers** [comment]
Of course, fixed within minutes after posting here. 

The trick was to use 
`@import FolioReaderKit; `
and set "Enable Modules" to YES (for the main target, not for the pods)

**Comment by hebertialmeida** [comment]
Would be great if you could write a simple Obj-c sample and make a PR, many people ask for that 😄
