### ISSUE TITLE
How to change default Green color in Folio UI

### ISSUE THREAD

**Issue by harishsave** [FolioReader/FolioReaderKit#248]
I want to change the default Green color in Folio viewer UI. How to do that?

**Comment by rjo** [comment]
Use the tintColor property. For example:

`   override public func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if(segue.identifier == "reader") {
            let container = segue.destination as? FolioReaderContainer
            FolioReader.shared.delegate = self
            let bookPath = Bundle.main.path(forResource:bookId, ofType: "epub")
            let config = FolioReaderConfig()
            config.tintColor = UIColor.red
            container?.setupConfig(config, epubPath: bookPath!, removeEpub: false)
        }
`

**Comment by hebertialmeida** [comment]
Thanks @rjo
