### ISSUE TITLE
Perform direct action instead of showing UIMenuController?

### ISSUE THREAD

**Issue by entonio** [FolioReader/FolioReaderKit#249]
Hi. I'm trying to create a reader focused on reading foreign language books, where being able to translate single words or entire paragraphs is the one and only concern. I'm only trying to write such a reader because I haven't found any that suits my use case. The now apparently inaccessible abookreader app (http://freapp.com/apps/ios/524345385/) did focus on translation, but it had quirks and is apparently abandoned. I've started with FolioReaderKit because it looks and feels so well fit.

What I would like is a 'translation mode' in which:
- pressing a word would show up its translation immediately
- stop pressing would clear the translation, getting back to the state before pressing
- touching with two fingers would do the same, but for the whole paragraph (or maybe sentence, that's probably more practical)

Originally I thought the translation might just replace the translated text. Then I though that might be too complicated, so I thought of using some overlay, that would really not be a poor alternative, anything in fact would do as long as it's readable and can be dismissed easily. Hence my question of how, instead of showing the context menu on tapping the text, one might:

- get the word or sentence (I see you use JS to select the word, which is something not everyone else does)
- if not in cache, send it to some translation service (configurable somewhere else, like bing or google, the language pair can be user-defined per book, for instance) (this everyone knows how to do, of course, I'm just including it to make the flow intelligible)
- present an overlay with the translation
- dismiss it all when the user lifts their finger(s)

I'm not sure this can be done at all with a webview, but I think at least some approximation should be possible, I'm just unsure where to start. If nothing else works, one might use the context menu itself to present the translation, as if it were an option, I suppose, at least for single words. But I'd like not to have to resort to that.

This 'translation mode' would be switchable somewhere, so that users might go back to the normal context-menu mode if needed.

I also wanted your opinion on whether this is doable from outside FolioReaderKt or should involve changing it directly. I apologise for the longwindedness.

**Comment by hebertialmeida** [comment]
I think it is totally doable with FolioReaderKit, you can take a look here: https://github.com/FolioReader/FolioReaderKit/blob/master/Example/Storyboard-Example/ExampleFolioReaderContainer.swift#L24

How to handle click on specific objects, but for fully satisfy your need you will have to do couple customizations.
