### ISSUE TITLE
 Changing the font size causes the page to appear in black and white when `paginationBreakingMode` is `.page` on night mode in iOS 10.3

### ISSUE THREAD

**Issue by zlyunduan** [FolioReader/FolioReaderKit#258]
The smallest font size causes the page to appear in black and white，increasing the font causes some of the content to be blocked.

**_white and black_**
![img_2899](https://user-images.githubusercontent.com/15976022/30096361-99e4902e-930a-11e7-8fb7-8456d37030e7.PNG)

**_blocked_**
![img_2900](https://user-images.githubusercontent.com/15976022/30096389-b25f10b6-930a-11e7-99e6-9fe7eda4a2f4.PNG)

@hebertialmeida #227

**Comment by Julyyq** [comment]
中国人用这个库的不少啊

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
