### ISSUE TITLE
Enhance audio player controls and icons

### ISSUE THREAD

**Issue by kjantzer** [FolioReader/FolioReaderKit#26]
![c9d0b4de-b922-11e5-897b-8aee7b3b3977](https://cloud.githubusercontent.com/assets/467487/12301489/306224c8-b9d5-11e5-9d1f-d372766eb004.png)

@hebertialmeida Do you have a source file with the icons in this mockup?

**Comment by hebertialmeida** [comment]
@kjantzer I have the source in .sketch, does it work for you?

**Comment by kjantzer** [comment]
I don't have the Sketch app

**Comment by hebertialmeida** [comment]
What do you need? The exported assets work for you?

**Comment by kjantzer** [comment]
Yeah, I think so

**Comment by hebertialmeida** [comment]
Here are the images.
[audio-player-icons.zip](https://github.com/FolioReader/FolioReaderKit/files/89236/audio-player-icons.zip)

**Comment by kjantzer** [comment]
@hebertialmeida We need a pause icon too ;)

**Comment by hebertialmeida** [comment]
Here.
[pause-icon.zip](https://github.com/FolioReader/FolioReaderKit/files/89282/pause-icon.zip)

**Comment by hebertialmeida** [comment]
Test the latest version please. Next and previous should work now.

On Readium the next and previous go to next text block, and only change the page if it is the last text block of that chapter, or the first in case of previous. What do you think?

**Comment by kjantzer** [comment]
Tested and it seem much better! :ok_hand: 

***

Here's my thoughts on the next/prev button...

As a user, I can begin playing anywhere by long pressing on a word and pressing "play". Text blocks change so fast that pressing prev or next barely does anything.

If I was to play a book from the beginning, I could see wanting to skip the current chapter if it was something like the intro, preface, or credits more than a text block (but maybe that's just me.)

**Idea**

1. Maybe the `prev/next` actions should be a setting to let the user choose what they do?
2. Or maybe we add another set of buttons?   
   `prevChap` `prevTextBlock` `playPause` `nextTextBlock` `nextChap`
 
What do you think?

**Comment by hebertialmeida** [comment]
I think that would be more useful to have a skip interval like in podcast app, or even iBooks app. Instead of next and previous.

![fullsizerender](https://cloud.githubusercontent.com/assets/103670/12362354/ef38ad6a-bba9-11e5-992c-9bf1f9419b6c.jpg)
