### ISSUE TITLE
 'FolioReader' initializer is inaccessible due to 'fileprivate' protection level

### ISSUE THREAD

**Issue by das-palash-appsbee** [FolioReader/FolioReaderKit#262]
When I write `let folioReader = FolioReader()` it throws _"FolioReader initializer is inaccessible due to 'fileprivate' protection level"_ error. 
I tried to remove **fileprivate** and made it **public** but then I got error on the next line:
`folioReader.presentReader(parentViewController: self, withEpubPath: bookPath!, andConfig: config)`
And the error was:
_Static member 'presentReader' cannot be used on instance of type 'FolioReader'_.

Using Xcode 8.3.3 with Swift 3.1

**Comment by odunsair** [comment]
+1

**Comment by hebertialmeida** [comment]
As you can see FolioReader() is a open class.
https://github.com/FolioReader/FolioReaderKit/blob/a78952113b3b23fa6bae65626e10b7292ec0a13e/Source/FolioReaderKit.swift#L94
