### ISSUE TITLE
Unable to start with iOS Folio Reader /Swift3/Xcode 9

### ISSUE THREAD

**Issue by zohdirizvi** [FolioReader/FolioReaderKit#266]
I am a newbie to Xcode and through various youtube videos I was able to install Cocoapod in my xcode and have also downloaded and installed the foliokit but when I started implementing the example code to get started, xcode is saying **No such module 'FolioReaderKit'** although I have included it as described. Can anyone please help me? is it because of Xcode 9 or Swift 3? Would be really thankful for the help.

**Comment by zohdirizvi** [comment]
<img width="1402" alt="screen shot 2017-09-27 at 5 30 14 pm" src="https://user-images.githubusercontent.com/32332499/30928029-65d5da3c-a3cb-11e7-8225-3ce8af34dc56.png">
<img width="1402" alt="screen shot 2017-09-27 at 5 30 29 pm" src="https://user-images.githubusercontent.com/32332499/30928030-66328a84-a3cb-11e7-9911-cb7ba727037e.png">

please see the screenshots..

**Comment by zohdirizvi** [comment]
@hebertialmeida Your help needed sir.

**Comment by worchyld** [comment]
you need to open the .xcworkspace that cocoapods creates not .xcodeproj

**Comment by hebertialmeida** [comment]
Is this still happening in the latest master, I believe this can be closed.
