### ISSUE TITLE
How to calculate the currentpage and totalpage for the whole book?

### ISSUE THREAD

**Issue by ansonham** [FolioReader/FolioReaderKit#267]
It seems that the `totalPages` and `currentpage` in the `FolioReaderCenter` class is for the specified chapter, not for the whole book.

**Comment by wedranb** [comment]
Good question, I'm also interested in this data since this is common data needed for the applications.

**Comment by HamGuy** [comment]
Do you have any idea about this? @wedranb

**Comment by wedranb** [comment]
@HamGuy  Not, atm. But I will be looking into it this or next week.

**Comment by wedranb** [comment]
Hey @hebertialmeida, this data is really important to know and it would be awesome to expose it somehow.

I'm not sure how to do this but if you could write on how to approach this maybe we could help.

Thanks! :)

**Comment by wedranb** [comment]
Hey @HamGuy I made some progress with this.

Try using `FolioReaderPageDelegate` on a VC where you are using FolioReader.

Then create `func pageDidLoad(_ page: FolioReaderPage)` to conform to protocol and assign page delegate `folioReader.readerCenter?.pageDelegate = self`

By doing this I think you can get data you wanted.

**Comment by hebertialmeida** [comment]
This is a really good thing to have but tricky to implement, because you have to load all the pages in advance and calculate each. 

iBooks does this in background thread somehow... Anyone interested in helping with this?

**Comment by carlhung** [comment]
@wedranb  hey. I want to have the page. but `folioReader.readerCenter` is empty. how can I initialise `folioReader.readerCenter`?
thanks.

**Comment by wedranb** [comment]
@hebertialmeida can you share some details about how to implement this? I don't know if I can go through codebase easily. But if you point into some directions how to implement this maybe I can help.

Thanks! :)

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
