### ISSUE TITLE
Night Mode white background glitches

### ISSUE THREAD

**Issue by mgiroux** [FolioReader/FolioReaderKit#269]
Although there is a semi-fix on master there is still a white border issue in night mode (horizontal)

to fix this the css should be the following

![screen shot 2017-10-10 at 5 45 00 pm](https://user-images.githubusercontent.com/4205308/31412359-c6078510-ade2-11e7-9fa9-4f9e448a1db5.png)

**Comment by mgiroux** [comment]
Issue should be closed if my PR is accepted

**Comment by hebertialmeida** [comment]
Can you reproduce that on the last master?

**Comment by hebertialmeida** [comment]
Closed due to inactivity.
