### ISSUE TITLE
Add "now playing" info to lock screen for audio synced epubs

### ISSUE THREAD

**Issue by kjantzer** [FolioReader/FolioReaderKit#27]
We will likely have a "cover" image specified in the OPF that we can use to display on the lock screen.

**Comment by hebertialmeida** [comment]
:+1:

**Comment by hebertialmeida** [comment]
Also we need to enable background audio capability.

**Comment by hebertialmeida** [comment]
@kjantzer It's working.
![Uploading IMG_4601.PNG…]()

**Comment by kjantzer** [comment]
@hebertialmeida Sweet! :tada:

**Comment by hebertialmeida** [comment]
@kjantzer Please test it...

**Comment by kjantzer** [comment]
@hebertialmeida Looks great.

**Comment by kjantzer** [comment]
I found a few bugs; I'm fixing them now.
