### ISSUE TITLE
Layout Issue After Integrating in Swift 4

### ISSUE THREAD

**Issue by joshnaNalla** [FolioReader/FolioReaderKit#271]
Hi,
I have Integrated FolioReaderKit in Xcode 9 and updated code to swift 4 , but getting layout issue with frames. Can anyone encountered with this problem please help me.
![screen shot 2017-10-12 at 3 57 17 pm](https://user-images.githubusercontent.com/32710126/31491759-0d3cb944-af66-11e7-8f7e-ce40b48cdfa5.png)

**Comment by mgiroux** [comment]
Since FolioReader is not Swift 4 compatible, you must tell cocoapods to build FR in swift 3.2 add this to your Podfile

post_install do |installer|
        myTargets = ['FolioReaderKit', 'FontBlaster', 'MenuItemKit']

        installer.pods_project.targets.each do |target|
                if myTargets.include? target.name
                        target.build_configurations.each do |config|
                                config.build_settings['SWIFT_VERSION'] = '3.2'
                        end
                end
        end
  end

the FR will work wihout a problem ;)

**Comment by hebertialmeida** [comment]
The last master is using swift 4 now.
