### ISSUE TITLE
Read epub from remote server

### ISSUE THREAD

**Issue by mgiroux** [FolioReader/FolioReaderKit#272]
It would be nice to have `withEpubURL` to load remote epub documents.

**Comment by naissa12** [comment]
how can we do this? I need it too

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
