### ISSUE TITLE
View mirrors in RTL and horizontal scroll mode when the orientation changes

### ISSUE THREAD

**Issue by ahmedk92** [FolioReader/FolioReaderKit#274]
I got that RTL support is achieved by mirroring the collection view, then mirroring each cell in the collection view. This works fine, but when the view rotates, the cell mirrors again.

**Comment by hebertialmeida** [comment]
Isn't the mirroring already implemented? It's always better to open a pull request so I can try your code and help.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
