### ISSUE TITLE
IOS 11 Issues: positions of highlights and last page read not working

### ISSUE THREAD

**Issue by florent2009** [FolioReader/FolioReaderKit#276]
Hello,

The last page read that used to be kept in memory, when you re-open an epub file is not working any more. Same thing for the highlights. The highlight links do not link to the correct position in the text.
This bug is only for IOS 11. On IOS 10, everything works perfectly.

Do any one know where this bug comes from?

Thank you by advance,

Best regards

**Comment by odunsair** [comment]
+1

**Comment by worksdelight-davinder** [comment]
Can you explain this how can I resolve this bug. I have spend 2 days on it but did not find any solution for this 

Thank you in advance

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
