### ISSUE TITLE
Realm version update

### ISSUE THREAD

**Issue by noxsicarius** [FolioReader/FolioReaderKit#278]
Is there a particular reason why realm 2.10 is used instead of realm 3? When using the realm browser it forces me to update the file to the newer format, breaking the app, because 2.10 can't read the new 3 format. This basically means I can't edit the files outside of the application, making testing a little annoying. I'm going to be trying to perform a realm version update on a forked copy of this repository in the meantime, but if anyone can help me with any information or testing they have performed, please do so.

Apparently version 3.0.2 of realm reverts folio back to v0.8.6 and I can't directly modify the folio dependencies without first rebuilding the pod with the new spec file and loading it locally. Hopefully this is a fast fix.

**Comment by noxsicarius** [comment]
It looks like realm 2.10 was used simply because the pod file was set up to only work with version 2.7 up to, but not including 3.0. This seems to have been an oversight of pod file syntax. I have since unlocked realm to allow any new versions of realm to be installed as there are no problems seen with the update. I have not modified any other pods as I have had no use to mess with them yet. I will work on dealing with updating and testing all pods to the latest versions as soon as I am done with my application. I am expecting that a few other pods are simply locked to what they are due to an oversight like realm.

**Comment by hebertialmeida** [comment]
Could you open a PR for that?
