### ISSUE TITLE
Search and Notes

### ISSUE THREAD

**Issue by worksdelight-davinder** [FolioReader/FolioReaderKit#282]
Hi all

I have implemented notes with this SDK and its working fine like iPhone iBooks notes and implement search with sdk but its not working properly

Book search is works well.

I have one issues I did not get range of words when click on the searched text please help me if any one have solution

**Comment by worksdelight-davinder** [comment]
Like highlight I want to switch on book with selected word after click on searched text

**Comment by hebertialmeida** [comment]
Cloud you open a Pull Request, so may I can help you with that.

**Comment by iOSDev-Madurai** [comment]
Hi @hebertialmeida ,

Me also want this feature can you please help me with this..?

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
