### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by worksdelight-davinder** [FolioReader/FolioReaderKit#283]
![simulator screen shot - iphone 6 - 2017-11-22 at 18 43 45](https://user-images.githubusercontent.com/30112230/33129229-3f79fa74-cfb5-11e7-8973-e5bb699562c0.png)
![simulator screen shot - iphone 6 - 2017-11-22 at 18 44 00](https://user-images.githubusercontent.com/30112230/33129241-481c375a-cfb5-11e7-92de-5ac53a1ef98c.png)
![simulator screen shot - iphone 6 - 2017-11-22 at 18 44 00](https://user-images.githubusercontent.com/30112230/33129248-4b882d0e-cfb5-11e7-81cb-f753d0f716d6.png)
![simulator screen shot - iphone 6 - 2017-11-22 at 18 44 14](https://user-images.githubusercontent.com/30112230/33129252-4d449e16-cfb5-11e7-8e9d-2d309ee9cbf1.png)
![simulator screen shot - iphone 6 - 2017-11-22 at 18 44 40](https://user-images.githubusercontent.com/30112230/33129257-4ef0cd5c-cfb5-11e7-8f10-b725a2e01c7c.png)

these are images that I have implemented with folio sdk notes bookmark and search.

please help me to resolve my search issue I need to go on specific page with highlighted colour like highlighted and notes functionality on the click of searched table text (didselectrow delegate)

**Comment by m1faridi** [comment]
Please send this project

**Comment by worksdelight-davinder** [comment]
I just want to resolve bus. are you able to help me to find out this bug

**Comment by m1faridi** [comment]
Yes I want to help

**Comment by worksdelight-davinder** [comment]
let htmlBodyResult = RegExp("<body(.|[\n])*</body>").matches(html!)


application is crashing on this line because I am parsing XML data 
when I use HTML its working fine but on xml file its crashing

**Comment by hebertialmeida** [comment]
Please open a Pull Request so we can help you debug and try to fix that.

**Comment by risechen** [comment]
@worksdelight-davinder  Did you implement the search result jump to the real page?

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
