### ISSUE TITLE
Urgent help needed: FolioReader crashing in iOS

### ISSUE THREAD

**Issue by zohdirizvi** [FolioReader/FolioReaderKit#284]
Hello,

Thank you so much for the great library, but recently after the release of iOS 11.1.2, the Folio is crashing in iOS when I try to open two or three .epub file..the problem is coming when I try to open scroll the book content, and opening another book, the app crashes.

Please see the code implemented in Xcode and the "null" error coming in Xcode.

![whatsapp image 2017-11-23 at 6 33 16 pm](https://user-images.githubusercontent.com/32332499/33181494-da64f154-d089-11e7-9851-51a85b050ba7.jpeg)

**Comment by zohdirizvi** [comment]
@hebertialmeida can you pls help?

**Comment by khallad** [comment]
@zohdirizvi i am getting the same error. did you manage to fix it?

**Comment by hebertialmeida** [comment]
is it still happening in latest master version?

**Comment by jasmine9502** [comment]
i have met the same question

**Comment by QuantumCPH** [comment]
@hebertialmeida yes it is still happening for version 1.2.0. 
If user press on cancel button while the screen was scrolling then that crash happens.

**Comment by QuantumCPH** [comment]
@hebertialmeida please respond asap.

**Comment by hebertialmeida** [comment]
Yesterday I have deployed a new version 1.3.0 this should be fixed. If it is not fixed I will need the books that are causing the crash.
