### ISSUE TITLE
Problems when use it with Carthage

### ISSUE THREAD

**Issue by prsolucoes** [FolioReader/FolioReaderKit#286]
Hi,

I put the carthage dependency on my Cartfile and after compile everything an error happen on FolioReaderKit. The log is hosted on my dropbox:

https://www.dropbox.com/s/c7tjb1v2swo5hvi/folio-kit-log.txt?dl=1

Lot of errors happen.

Thanks.

**Comment by hebertialmeida** [comment]
#287 Should fix your problem :)
