### ISSUE TITLE
Disable screen dimming when playing audio

### ISSUE THREAD

**Issue by kjantzer** [FolioReader/FolioReaderKit#29]
If the person is reading only or listening only, this is not needed. But if the users is listening and reading along, there will be very limited action by the user since the audio player will auto-scroll the page.

If this is the case, we don't want the screen to auto-dim.

```
UIApplication.sharedApplication().idleTimerDisabled = true
```

http://stackoverflow.com/a/28332647/484780

**Comment by hebertialmeida** [comment]
:+1:  It's true, we can't forget it disabled, when audio stops or closes the book we need to enable it.
