### ISSUE TITLE
The difference between pages in navigation display and hiding

### ISSUE THREAD

**Issue by lufeifeiyue** [FolioReader/FolioReaderKit#290]
The content of the page is distinctly different when the navigationBar is displayed and hidden, and it is expected to solve this problem,thank you.

![simulator screen shot - iphone 8 - 2017-12-16 at 10 40 46](https://user-images.githubusercontent.com/16662834/34066689-9e0aecf6-e24d-11e7-941b-f769e07a35e7.png)

![simulator screen shot - iphone 8 - 2017-12-16 at 10 40 50](https://user-images.githubusercontent.com/16662834/34066688-9dc01212-e24d-11e7-8adc-92eaa617430c.png)

**Comment by hebertialmeida** [comment]
Hi @lufeifeiyue, what is expected to fix what? Could you add some context for me?

**Comment by hebertialmeida** [comment]
Closed due to inactivity.
