### ISSUE TITLE
Not installed by Carthage

### ISSUE THREAD

**Issue by chuikoffru** [FolioReader/FolioReaderKit#291]
xCode 9.2, Swift 4
Create New project

iMac-Konstantin:bible chuikoff$ touch Cartfile
iMac-Konstantin:bible chuikoff$ nano Cartfile
iMac-Konstantin:bible chuikoff$ carthage update --platform iOS --no-use-binaries
*** Cloning FolioReaderKit
*** Cloning AEXML
*** Cloning ZFDragableModalTransition
*** Cloning FontBlaster
*** Cloning JSQWebViewController
*** Cloning ZipArchive
*** Cloning MenuItemKit
*** Cloning realm-cocoa
*** Checking out ZipArchive at "v1.8.1"
*** Checking out MenuItemKit at "2.0"
*** Checking out realm-cocoa at "v2.10.2"
*** Checking out JSQWebViewController at "5.0.0"
*** Checking out FontBlaster at "3.0.0"
*** Checking out FolioReaderKit at "1.2.0"
*** Checking out ZFDragableModalTransition at "8da951efb4202385630d1cf7104b60d1208f807e"
*** Checking out AEXML at "4.0.0"
*** xcodebuild output can be found in /var/folders/5l/_b602_5j631bgz5_jp28ftg40000gn/T/carthage-xcodebuild.T9tGPk.log
*** Building scheme "AEXML iOS" in AEXML.xcodeproj
*** Building scheme "FontBlaster" in Font Blaster Sample Project.xcodeproj
*** Building scheme "JSQWebViewController" in JSQWebViewController.xcworkspace
*** Building scheme "MenuItemKit" in MenuItemKit.xcodeproj
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
*** Building scheme "ZFDragableModalTransition-iOS" in ZFDragableModalTransition.xcodeproj
*** Building scheme "ZipArchive-iOS" in ZipArchive.xcodeproj
*** Building scheme "FolioReaderKit" in FolioReaderKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/chuikoff/Developer/bible/Carthage/Checkouts/FolioReaderKit/FolioReaderKit.xcodeproj -scheme FolioReaderKit -configuration Release -derivedDataPath /Users/chuikoff/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/FolioReaderKit/1.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/5l/_b602_5j631bgz5_jp28ftg40000gn/T/FolioReaderKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/chuikoff/Developer/bible/Carthage/Checkouts/FolioReaderKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/5l/_b602_5j631bgz5_jp28ftg40000gn/T/carthage-xcodebuild.T9tGPk.log

How fix it?

**Comment by hebertialmeida** [comment]
The latest master version should be working.
