### ISSUE TITLE
Showing blank pages 

### ISSUE THREAD

**Issue by worksdelight-davinder** [FolioReader/FolioReaderKit#292]
Hi dear developer

I am facing some issue when I parse book from pub second page of book will be black after cover of image when I scrolled it in horizontal

**Comment by noxsicarius** [comment]
I have a similar issue where the end of every "chapter" is a blank page. I'm currently looking into it myself and will post a fix if I find one.

**Comment by hebertialmeida** [comment]
This is an annoying bug, not sure if is the same as the end of every chapter, it is a WebView bug I believe. I am not aware of any workaround. Did you find any solution @noxsicarius?

**Comment by noxsicarius** [comment]
I did not. I was pulled into something else. I'll come back to it at some point if there is no other fix.

**Comment by exherb** [comment]
first page is also blank？

**Comment by HarshaYogesha** [comment]
during fast scroll page appears  blank..if you fix it please share

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
