### ISSUE TITLE
How to add FolioReader as a subview in my custom view

### ISSUE THREAD

**Issue by joshnaNalla** [FolioReader/FolioReaderKit#293]
hi, i want to add folioReader as a subview to my viewcontroller how can i do this.. can any one help me

Thanks

**Comment by wesleycgs** [comment]
I do this with ContainerView, see Storyboard-Example in Demo project.
Then you can add your views above and behind container ;D

![image](https://user-images.githubusercontent.com/23085121/35101177-bb383222-fc45-11e7-9a14-dce59d5afac7.png)

**Comment by hebertialmeida** [comment]
Thanks @wesleycgs, yeah this is the best way.
