### ISSUE TITLE
Latest Realm Dependency

### ISSUE THREAD

**Issue by ahamedsaifudeen** [FolioReader/FolioReaderKit#294]
We use FolioReaderKit in our app and we also use Realm (Swift) in our app. Looks like FolioReaderKit is also using Realm (Swift) and it is pulling the older version of Realm Swift (which creates some issues in our project), can you please ensure the latest realm is used in FolioReaderKit?

I am not sure if there is a workaround to solve my problem.

**Comment by hebertialmeida** [comment]
Master should be using the updated version now

**Comment by ahamedsaifudeen** [comment]
Thanks. I don't get the latest realm in latest version FolioReaderKit. Can you please let me know when you will be updating the pod version?
