### ISSUE TITLE
Can't compile after updating to Xcode 9 - errors in dependencies?

### ISSUE THREAD

**Issue by CHPraxis** [FolioReader/FolioReaderKit#298]
I upgraded to Xcode 9, and am no longer able to compile my project.  It seems like the issue is with AEXML and FontBlaster, which are being imported when I get FolioReaderKit in my Podfile.

AEXML has this error:
/Users/MyName/Programming/ProjectName/Pods/AEXML/Source/AEXML.swift:128:54: Function types cannot have argument labels; use '_' before 'element'

and this warning:
/Users/MyName/Programming/ProjectName/Pods/AEXML/Source/AEXML.swift:200:26: Extraneous duplicate parameter name; 'name' already has an argument label

FontBlaster has 19 errors, with items like these:

/Users/MyName/Programming/ProjectName/Pods/FontBlaster/FontBlaster.swift:50:38: 'NSBundle' has been renamed to 'Bundle'
/Users/MyName/Programming/ProjectName/Pods/Foundation.NSBundle:2:18: 'NSBundle' was obsoleted in Swift 3
/Users/MyName/Programming/ProjectName/Pods/FontBlaster/FontBlaster.swift:106:32: 'Font' is inaccessible due to 'private' protection level
/Users/MyName/Programming/ProjectName/Pods/FontBlaster/FontBlaster.swift:40:23: Type declared here
/Users/MyName/Programming/ProjectName/Pods/FontBlaster/FontBlaster.swift:139:76: 'Font' is inaccessible due to 'private' protection level
/Users/MyName/Programming/ProjectName/Pods/FontBlaster/FontBlaster.swift:40:23: Type declared here
/Users/MyName/Programming/ProjectName/Pods/FontBlaster/FontBlaster.swift:163:48: 'FontName' is inaccessible due to 'private' protection level
/Users/MyName/Programming/ProjectName/Pods/FontBlaster/FontBlaster.swift:38:23: Type declared here
/Users/MyName/Programming/ProjectName/Pods/FontBlaster/FontBlaster.swift:66:32: 'NSFileManager' has been renamed to 'FileManager'
/Users/MyName/Programming/ProjectName/Pods/Foundation.NSFileManager:2:18: 'NSFileManager' was obsoleted in Swift 3

It seems like it is getting old versions of AEXML and FontBlaster which aren't Swift 3 compatible.  Any idea why this is?  I tried deleting everything and doing a new pod install and still got the same files.

**Comment by hebertialmeida** [comment]
Are you sure that your project is migrated to swift 4? The latest `master` version of FolioReaderKit requires swift 4 to work as well the project dependencies.

If you need swift 3 support you will have to use a swift 3 compatible build, but not the `master`.

**Comment by CHPraxis** [comment]
My apologies, my fault- looks like I forgot to run pod update and still had an older version.
