### ISSUE TITLE
how to show title of the epub at the top bar 

### ISSUE THREAD

**Issue by khallad** [FolioReader/FolioReaderKit#299]
i can see that the title of the epub is showing in the bar at the top of the screen in the demo section that is provided. How can i make it appear in my app because it is not being displayed

**Comment by hebertialmeida** [comment]
Sorry, that gif is an old one and needs to be updated, we have changed the UI a lot and that is not available anymore because we have many buttons on the navigation bar.

**Comment by hebertialmeida** [comment]
Closed due to inactivity.
