### ISSUE TITLE
`updateCurrentPage` has some issues

### ISSUE THREAD

**Issue by kjantzer** [FolioReader/FolioReaderKit#30]
While playing around with audio controls, occasionally `updateCurrentPage` is called and sets `currentPage` to a wrong page. Usually it sets it to one that just "loaded" but is not yet visible (such as when near the end of the chapter)

This causes issues with `next` and `prev` in #26

**Comment by hebertialmeida** [comment]
How do I simulate this?

**Comment by kjantzer** [comment]
If you open sherlock holmes and mess around with changing pages and scrolling, you'll see the current page mess up. One way to see the bug is the title in the nav bar will change even though the chapter did not change

![bug mov](https://cloud.githubusercontent.com/assets/467487/12306938/47d69eec-b9f1-11e5-94e2-91b6c4d391d6.gif)

**Comment by kjantzer** [comment]
It's very noticeable if you trigger `changePageToPrevious` which can be easily done using my latest commit:
https://github.com/kjantzer/FolioReaderKit/commit/79ae3e9bc8aca0a3d0c4a629e6b284aee5efb9e5

Notice how the `prev` button is pressed twice to change pages and that the title changes on every other press.

![bug2 mov](https://cloud.githubusercontent.com/assets/467487/12307125/40f5e5dc-b9f2-11e5-985b-9bb672ffa2a4.gif)

**Comment by hebertialmeida** [comment]
@kjantzer  Take a look on this last commit, I think that now it's fixed.

**Comment by kjantzer** [comment]
`changePageToPrevious` is still buggy :disappointed:

**Comment by hebertialmeida** [comment]
Why the next and previous navigate between pages?

**Comment by kjantzer** [comment]
Why am I navigating between pages?

**Comment by hebertialmeida** [comment]
Yes, but if you have finished the implementation you can send a pull request and I will try to fix it.
