### ISSUE TITLE
Bug in getCurrentChapter(), not returning some chapters.

### ISSUE THREAD

**Issue by wesleycgs** [FolioReader/FolioReaderKit#302]
Chapters are in flatTableOfContents ok? But some chapters theres in children, and your method to get current chapter was not searching in toc children.

**ORIGINAL CODE:**
`func getCurrentChapter() -> FRResource? {`

    for item in self.book.flatTableOfContents {
        if
            let reference = self.book.spine.spineReferences[safe: (self.currentPageNumber - 1)],
            let resource = item.resource,
            (resource == reference.resource) {
            return item.resource
        }
    }
    return nil
}`

**THEN FIX WITH THIS**, searching in each toc children
`
func getCurrentChapter() -> FRResource? {
        var _resource: FRResource?
        
        func search(_ items: [FRTocReference]) {
            for item in items {
                //Has found! return
                if _resource != nil {
                    break
                }
                
                if
                    let reference = self.book.spine.spineReferences[safe: (self.currentPageNumber - 1)],
                    let resource = item.resource,
                    (resource == reference.resource) {
                    _resource = item.resource
                    break
                } else if let children = item.children, children.isEmpty == false {
                    //Search in children
                    search(children)
                }
            }
        }
        search(self.book.flatTableOfContents)
        
        return _resource
    }`

**Comment by hebertialmeida** [comment]
Awesome, can you open a PR, it's always nice to have more contributors 😄
