### ISSUE TITLE
long-tap issue for select word

### ISSUE THREAD

**Issue by dipakviprak** [FolioReader/FolioReaderKit#307]
the long-tap issue for select word tap time then move another page and tap long in specific word then scroller another page automatically (Ex. Hack: are we able to trigger SHORT-tap automatically when scroll happens?  I believe that will set a new anchor point of words and solve the issue )

**Comment by hebertialmeida** [comment]
Can you explain a little bit more what is your problem and how to reproduce that?

**Comment by dipakviprak** [comment]
I have fixed this issues, thank you for replying me...

**Comment by hebertialmeida** [comment]
Can you open a PR for the fix? So other people can benefit from that.

**Comment by dipakviprak** [comment]
FoliaReaderKit inside FoliareaderWebview.swift File add one scroller view method and scroller page in specific book clear selection text 
👍add this method 👍 
func scrollViewDidScroll(_ scrollView: UIScrollView)
