### ISSUE TITLE
how can we set the reading as word, sentence and paragraph mode?

### ISSUE THREAD

**Issue by sreejithsree123** [FolioReader/FolioReaderKit#310]
Now the epub reader is reading sentence so If the reader need word by word that should be reflected and for paragraph also so how can I do that. :) @hebertialmeida share if have any option for this or I have to want to do it another way please send the feedback. @katopz

**Comment by hebertialmeida** [comment]
Right now the implementation uses sentences because the TTS feels more natural, but you should be able to achieve this modifying the current implementation.

There is no easy way to use that, so you will have to implement.
