### ISSUE TITLE
Incorrect menu on second highlight

### ISSUE THREAD

**Issue by pklarl** [FolioReader/FolioReaderKit#316]
Setting a highlight and then immediately mark a second text passage, the wrong menu will be displayed: Highlight color selection instead of selection edit option.
Now selecting a color, the previously created highlight will be adjusted.

Only after re-selection of the first highlight (editing option highlight is displayed) or after a page change, the error is fixed ([Video Highlight Menu](https://youtu.be/qwklOCt7dEw)).

Is the problem known, and if so, is there a (foreseeable) solution?

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
