### ISSUE TITLE
detect selected text.

### ISSUE THREAD

**Issue by carlhung** [FolioReader/FolioReaderKit#317]
I want to detect and copy the selected text and do something for the it. and remove the selected text bubble.
how can I do there?
thanks.

**Comment by carlhung** [comment]
oh! I found a way to do it. thanks.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
