### ISSUE TITLE
Option to copy the selected text in UIMenuItem and an issue with share

### ISSUE THREAD

**Issue by ahamedsaifudeen** [FolioReader/FolioReaderKit#318]
I request to add 'Copy' option in the UIMenuItem. Currently, selected text can be copied through iOS share menu (if share option is enabled in FolioReaderKit). If the share option is disabled, there is no way to copy the selected text. Please add 'Copy' option in UIMenuItem.

There is an issue with 'Share' option (in UIMenuItem). If we don't select any text and hit share, the entire book content is being shared. We don't want to share the entire book content as it may affect the app usage. Request you to look into this as well.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
