### ISSUE TITLE
Reader takes over the audio control

### ISSUE THREAD

**Issue by arthurlataks** [FolioReader/FolioReaderKit#321]
Pod takes control over the sound controls right after being initialised. This is due to having this line:

```swift     
// File: FolioReaderAudioPlayer.swift:46
try? session.setActive(true)
```
I removed that line and now this does not happen anymore. I also added this piece of code in order to alter menu and player state on audio session interruption:

```swift
// File: FolioReaderAudioPlayer.swift:47
NotificationCenter.default.addObserver(self,
    selector: #selector(pause),
    name: .AVAudioSessionInterruption,
    object: session
)
```

@hebertialmeida  do you see these changes to be fit for a pull request? If so, I will prepare one.

**Comment by EmersonCarpes** [comment]
@arthurlataks I did some tests and talk with @hebertialmeida, that's ok. Could you prepare the pull request please? Thanks.
