### ISSUE TITLE
If I want to show image in full screen, what should I do?

### ISSUE THREAD

**Issue by jhchenchong** [FolioReader/FolioReaderKit#325]

**Comment by EmersonCarpes** [comment]
This feature isn't implemented yet, On #37 we have discussed it. I started work on this, but, stopped because I'm out of free time.

**Comment by jhchenchong** [comment]
Thanks Reply,  I try to implement it but I am not good at Swift

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
