### ISSUE TITLE
Chapter list 

### ISSUE THREAD

**Issue by worksdelight-davinder** [FolioReader/FolioReaderKit#326]
In android chapter list is showing properly with the change of value 3 to 4
   if (tocLinkWrapper1.getIndentation() != 4) {
                    tocLinkWrapper.addChild(tocLinkWrapper1);
                }
 but in iOS it is not working can you please give me idea how it will work in iOS too

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
