### ISSUE TITLE
Highlighted two paragraph

### ISSUE THREAD

**Issue by worksdelight-davinder** [FolioReader/FolioReaderKit#327]
in iOS highlighted from one paragraph is working fine but when I select from the 2 paragraph its is not working properly

**Comment by EmersonCarpes** [comment]
Yes, this is a known bug since #37 there is a discussion there about it.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
