### ISSUE TITLE
Search in chapter

### ISSUE THREAD

**Issue by chintan217** [FolioReader/FolioReaderKit#329]
hi,

I have implemented notes with this SDK and its working fine. but,
I need to go on specific page with highlighted colour like highlighted  functionality on the click of searched table text

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
