### ISSUE TITLE
Not working perfectly.

### ISSUE THREAD

**Issue by Pinturaj** [FolioReader/FolioReaderKit#330]
I am using latest version of folio reader, but its viewing ePub like pdf. It doesnt show any extra epub functionality not even header view like.
After opend the epub there is no option to close the epub.

Thanks

**Comment by EmersonCarpes** [comment]
Hello @Pinturaj 
It sounds like a problem with the format of the pub that you are trying to open.
Could you share the epub file so I can make some tests? 
Thanks!

**Comment by Pinturaj** [comment]
@EmersonCarpes 
Now my problem is resolves.
Thanks.
