### ISSUE TITLE
Content is put down in ios 11 in play mode

### ISSUE THREAD

**Issue by dungnt109** [FolioReader/FolioReaderKit#332]
I tried the latest release of FolioReaderKit on iphone 6 ios 11. I long-pressed a word and tapped "Play" button. The content was automatically put down (see [screenshot](https://www.dropbox.com/s/xbxnxxsbf539t28/Simulator%20Screen%20Shot%20-%20iPhone%206%20Plus%20-%202018-04-11%20at%2019.49.07.png?dl=0)) 

This issue only occurs when I tested it on ios 11 and above. On ios 10, it is ok.

**Comment by EmersonCarpes** [comment]
Hello @dungnt109 
I made some tests with the FolioReader/Example and it works fine for me, could you share more information about the problem or maybe share your epub file to I make some tests here?
Thanks.

**Comment by dungnt109** [comment]
You can download my epub[ here](https://www.dropbox.com/s/khycznvxn5a6nd6/3.epub?dl=0)
The version of FolioReader I use is 1.3.0 
iPhone model: iphone 6, 6 plus 
ios version: 11.3 

FolioReader config: vertial scrolling

First open the epub file, scroll to the middle of the chapter, then long press any word and tap "play" button. The content is automatically put down. You can watch a video [here](https://www.dropbox.com/s/73srry80dvj2zv2/2.mov?dl=0)
