### ISSUE TITLE
When I make fast scroll my pages it jumping between chapters.

### ISSUE THREAD

**Issue by hellbit** [FolioReader/FolioReaderKit#333]
Hello guys! Did you find any solution? 

// Perform the page after a short delay as the collection view hasn't completed it's transition if this method is called (the index paths aren't right during fast scrolls).

When I make fast scroll my pages it jumping between chapters.

**Comment by sunho** [comment]
Disabling user interaction of FolioReaderCenter when its collection view start scrolling until it completes scrolling fixed the issue. But now scrolling between pages is not smooth.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
