### ISSUE TITLE
Let user choose the audio synced highlight style

### ISSUE THREAD

**Issue by kjantzer** [FolioReader/FolioReaderKit#34]
Right now we have one built in style
***
![screen shot 2016-01-14 at 3 16 39 pm](https://cloud.githubusercontent.com/assets/467487/12340868/6d849aa4-bad2-11e5-99a5-3546f8ac6125.png)
***
but it might be nice to allow the user to select a less obtrusive highlight style such as:
***
![screen shot 2016-01-14 at 3 17 50 pm](https://cloud.githubusercontent.com/assets/467487/12340870/723cec7c-bad2-11e5-8c6b-2cc2f76e2b33.png)

![screen shot 2016-01-14 at 3 19 11 pm](https://cloud.githubusercontent.com/assets/467487/12340869/7226a764-bad2-11e5-99b7-1b7e2f677f3b.png)

**Comment by hebertialmeida** [comment]
Interesting, I can design something like day/night mode

**Comment by hebertialmeida** [comment]
@kjantzer What do you think?

![audio controls](https://cloud.githubusercontent.com/assets/103670/12429894/dd407ade-bed3-11e5-84e2-e3ce5cc82387.png)

**Comment by kjantzer** [comment]
I Like it, except I can't tell which one is selected. And the far right doesn't even look like a style.

What if we left all three colored (like they would appear in the chapter) and add a "checkmark" to the left side of the "selected" style?

**Comment by hebertialmeida** [comment]
I tried all with color but it's too aggressive. We are not using a checkmark on any menu but we can try and see.

This are the interactions to see what is selected:
![screen shot 2016-01-19 at 18 00 52](https://cloud.githubusercontent.com/assets/103670/12430421/ac1a119c-bed6-11e5-915b-7d3701d933c3.png)

**Comment by kjantzer** [comment]
That's might not be bad, once a user clicks around, the style should make sense. Maybe lets try it like that for now and we can see if we get feedback on it.

**Comment by hebertialmeida** [comment]
For sure! 

Will you implement this?

**Comment by kjantzer** [comment]
:+1:

**Comment by kjantzer** [comment]
![34 mov](https://cloud.githubusercontent.com/assets/467487/12598546/c3b4a33a-c43f-11e5-80fa-7a2d43054612.gif)

**Comment by hebertialmeida** [comment]
Tested it, really cool!
