### ISSUE TITLE
Unspported Architecture while subimitting to AppStore

### ISSUE THREAD

**Issue by joshnaNalla** [FolioReader/FolioReaderKit#340]
I have build in 9.4.1 xcode version and have used framework of folioreaderkit but while submitting to the appstore I throws error like the below image .

can any one faced the problem please tell me the solution
![screen shot 2018-06-28 at 12 28 05 pm](https://user-images.githubusercontent.com/32710126/42035696-353e43e2-7b01-11e8-94c2-ea96ef75ed39.png)

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
