### ISSUE TITLE
Module complied with swift 4.0.1 can no be imported in swift 4.1.2

### ISSUE THREAD

**Issue by joshnaNalla** [FolioReader/FolioReaderKit#341]
Hi I am getting error while adding ipa to appstore which has folioreader framework of x86_64 if i add arm64 it shows as Module complied with swift 4.0.1 can no be imported in swift 4.1.2 in project..

Please can any one give me the latest swift code with framework of arm64

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
