### ISSUE TITLE
all features not working

### ISSUE THREAD

**Issue by chintan217** [FolioReader/FolioReaderKit#344]
Hi dear developer

i export .epub file from pages 
open in folioreader kit
book content show fine but, all feature not working 
cresh on  let json = try JSONSerialization.jsonObject(with: jsonData!, options: []) as! NSArray
becouse jsonData is nill can't call any js functions
plz check my .epub file & test him
thanks
[test5.zip](https://github.com/FolioReader/FolioReaderKit/files/2157937/test5.zip)

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
