### ISSUE TITLE
The rect of coverView is incorrect when change the font size

### ISSUE THREAD

**Issue by risechen** [FolioReader/FolioReaderKit#346]
![image](https://user-images.githubusercontent.com/31931021/43070819-6424dca6-8ea3-11e8-8316-fb383531752d.png)

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
