### ISSUE TITLE
How can I get the epub file like with <The Silver Chair.epub>

### ISSUE THREAD

**Issue by ancheng1114** [FolioReader/FolioReaderKit#349]
I am getting the epub file from pdf file, but the file structure is different with sample ebook file.
How can I make epub file like the sample ebook file of folioreaderkit?
Please let me know if you have the time. Thanks.

**Comment by tanmoynandi** [comment]
Sorry, but your question is not totally clear to me. But if you want to know about epub structure please follow this link, http://apex.infogridpacific.com/df/ePub3Packaging1.html

Tip: If you want to check the structure yourself, unzip an epub. ;)
