### ISSUE TITLE
How pagination for a particular htm or xhtml works?

### ISSUE THREAD

**Issue by tanmoynandi** [FolioReader/FolioReaderKit#350]
How does the content of one XHTML file is divided into multiple pages in an epub reader like this one?

I can understand how to get the total page number for one XHTML file or one chapter for an epub but how to get current page number while showing an XHTML?

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
