### ISSUE TITLE
Get sentence of selected text

### ISSUE THREAD

**Issue by jelnur** [FolioReader/FolioReaderKit#353]
How can I get sentence containing the selected word?
I see playAudio() selects sentence on Play but I can't get the sentence myself

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
