### ISSUE TITLE
How to get plain text of a chapter?

### ISSUE THREAD

**Issue by kevan18081990** [FolioReader/FolioReaderKit#354]

**Comment by jelnur** [comment]
You get html of chapter using
`htmlContentForPage(_ page: FolioReaderPage, htmlContent: String) -> String`

Then you can extract text from html with a tool like [HTMLReader](https://github.com/nolanw/HTMLReader)

Hope this helps

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
