### ISSUE TITLE
Crash opening a valid epub

### ISSUE THREAD

**Issue by RodPatagonia** [FolioReader/FolioReaderKit#355]
Hi,

I get a crash when opening a valid epub with 

ERROR: Could not find table of contents resource. The book don't have a TOC resource."

But I have validated the file successfully here: http://validator.idpf.org
I can also see the toc file.

<img width="424" alt="screen shot 2018-08-26 at 7 00 40 pm" src="https://user-images.githubusercontent.com/40782598/44633476-65867580-a962-11e8-87a6-7a57ac5f7215.png">

Please find attached a screenshot with the error and the toc file.

Thanks a lot

<img width="1190" alt="screen shot 2018-08-26 at 6 41 29 pm" src="https://user-images.githubusercontent.com/40782598/44633431-8e5a3b00-a961-11e8-9644-c08cdc61dce3.png">

**Comment by RodPatagonia** [comment]
I'm in the middle of that. I'll send a pull request I guess when I'm done.
It seems to work.

I'll send you the file to your email

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
