### ISSUE TITLE
Deprecated Framework - JSQWebViewController

### ISSUE THREAD

**Issue by ahamedsaifudeen** [FolioReader/FolioReaderKit#356]
JSQWebViewController is deprecated and is no longer maintained. It is not updated to support the latest swift version.

It is better to move WKWebView as quickly as possible.

**Comment by zhouweidong** [comment]
The same problem, how to solve it.

**Comment by ahamedsaifudeen** [comment]
@zhouweidong What issue are you facing?

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
