### ISSUE TITLE
FontBlaster - Not maintained

### ISSUE THREAD

**Issue by ahamedsaifudeen** [FolioReader/FolioReaderKit#357]
FontBlaster framework is not maintained and it is not updated to support latest swift release. Probably it is better to move to a different framework and own implementation to easier maintenance.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
