### ISSUE TITLE
xcode10?

### ISSUE THREAD

**Issue by younghaopro** [FolioReader/FolioReaderKit#358]

**Comment by TACGalang** [comment]
Any update for Swift 4.2? RealmSwift is failing.

**Comment by johnbanks** [comment]
On Xcode 10 and Swift 4.2 - I overcame the RealmSwift issue by reinstalling but I am having a strange problem in Extensions where the showBottomHairline function is failing, navigationBarImageView is nil and the forced unwrapping of it is failing.

```swift

internal extension UINavigationBar {

    func showBottomHairline() {
        let navigationBarImageView = hairlineImageViewInNavigationBar(self)
        navigationBarImageView!.isHidden = false
    }

```

**Comment by johnbanks** [comment]
Commented out the call to showBottomHairline and could get the reader to open successfully.  Unfortunately, clicking on Text resizing button resulted in another error

So yeah, I believe this needs to be updated for 4.2.  I simply can't really figure out why these failures are happening in my existing app.

**Comment by TACGalang** [comment]
Hi, any update for your dependency? RealmSwift is a bit to old, and its failing on XCode 10.

**Comment by TACGalang** [comment]
Hi @johnbanks, how did you fix it on XCode 10?

**Comment by massacreformash** [comment]
I think we should update Realm to the newest release or at least 3.7.1 version.
the 3.1.1 version is too old for Xcode 10

**Comment by zuil7** [comment]
> On Xcode 10 and Swift 4.2 - I overcame the RealmSwift issue by reinstalling but I am having a strange problem in Extensions where the showBottomHairline function is failing: navigationBarImageView is nil and the forced unwrapping of it is results in an exception. Any ideas would be appreciated.
> 
> ```swift
> internal extension UINavigationBar {
> 
>     func showBottomHairline() {
>         let navigationBarImageView = hairlineImageViewInNavigationBar(self)
>         navigationBarImageView!.isHidden = false
>     }
> ```

@johnbanks how did you solve this issue? i also encountered this.

**Comment by AdnanMajeed06** [comment]
To update realm , remove FolioReaderKit and then install latest Realm version. 
`pod 'Realm/Headers' , '~> 3.11.0'
`
after that you install realm. It will solve realm issue. But still you will find alot of other issue as FolioReaderKit not supporting iOS12 :(

**Comment by hebertialmeida** [comment]
Thanks guys for troubleshooting this. If you have implemented the fixes or use this project please open a PR.

> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
