### ISSUE TITLE
White background in Reader View (Night Mode)

### ISSUE THREAD

**Issue by oNguyenDuyKhanh** [FolioReader/FolioReaderKit#359]
Hi guys,
Im currently facing a problem in reader view, there were two white spaces in both side of the reader view  in the Night Mode. 
I searched and tried the solution in #269 but it still no uses. Idk this problem come from the epub itself or the webView. So pls can anyone help me resolve this. Thank you so much.
![screen shot 2018-09-21 at 3 05 38 pm](https://user-images.githubusercontent.com/33301231/45868915-299fce00-bdb1-11e8-8acd-af15b9de0cdf.png)

**Comment by khanhnd0506** [comment]
@hebertialmeida are you still supporting this Library?

**Comment by hebertialmeida** [comment]
I do, I just don't work full time on this project. But I would love to approve a pull request from you with this fix.

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
