### ISSUE TITLE
Memmory leak

### ISSUE THREAD

**Issue by volkzayaz** [FolioReader/FolioReaderKit#360]
Hi @hebertialmeida.

Great library, thanks for all the work that's been done.

I noticed a minor memory leak in FolioReaderPageIndicator.swift. 
When you add `let animation = CABasicAnimation(keyPath: "shadowColor")` you set the `delegate` to be `self`. But you never remove this animation from `layer`.
`CAAnimation` retains it's delegate hence causing memory leak. `FolioReaderPageIndicator` has strong references to `FolioReader` and `FolioConfig` which are leaked as well. 

Cheers

**Comment by hebertialmeida** [comment]
Thanks for reporting that.

> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
