### ISSUE TITLE
Crashes in MenuItemKit

### ISSUE THREAD

**Issue by igoMobile** [FolioReader/FolioReaderKit#362]
I experience issues with MenuItemKit. I just use UIMenuController in a particular view controller of mine, but MenuItemKit library is getting involved (why?). The crashes take place in the function makeUniqueImageTitles of MenuItemKit. The issue with crashes in makeUniqueImageTitles might be fixed in the version 3.1.2. But the current master brach of FolioReader contains dependency on version 3.0.0. Is it possible to update the dependency? Thanks!

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
