### ISSUE TITLE
it can't find file path

### ISSUE THREAD

**Issue by zahraasg** [FolioReader/FolioReaderKit#364]
Hi , I am using your storyboard example , and I import my epub file in my project , but anything happens just a loading indicator appears and then I have this message in my console : the file path is empty .
what should I do ???

**Comment by adrianorezena** [comment]
Please check the Target Membership if epub file is selected

**Comment by hebertialmeida** [comment]
Thanks @adrianorezena!

> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
