### ISSUE TITLE
Base64 read source support

### ISSUE THREAD

**Issue by ongyen8888** [FolioReader/FolioReaderKit#367]
My previous feature request was about Apple's DRM but since I was told that Apple's DRM is private and can't be done, what about Readium LCP DRM that's mentioned in Folio Reader Android? When is this going to be released? And base64 read source support?

**Comment by hebertialmeida** [comment]
> Disclaimer: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
