### ISSUE TITLE
Xcode 10.1 - Swift 4.2 bug in List.swift

### ISSUE THREAD

**Issue by veila** [FolioReader/FolioReaderKit#370]
Bug in List.swift
Invalid redeclaration of 'removeSubrange'
Invalid redeclaration of 'replaceSubrange(_:with:)'

Bug in Optional.swift

Use of unresolved identifier 'underlyingValue'; did you mean 'KernKerningValue'?

**Comment by betzerra** [comment]
Yup, it seems to be a dependency issue https://github.com/realm/realm-cocoa/issues/5968
<img width="266" alt="screenshot 2018-11-06 17 56 23" src="https://user-images.githubusercontent.com/681600/48093223-90583a00-e1ed-11e8-9871-ca622ba19a27.png">

**Comment by hebertialmeida** [comment]
> Note: I am closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out or open a PR and we can discuss it there.
