### ISSUE TITLE
Alert Error : Cannot read container.xml

### ISSUE THREAD

**Issue by zahraasg** [FolioReader/FolioReaderKit#372]
Hi , I download a file from server and I unzip it , After this I want it to open in pub reader but It says : Cannot read container.xml .
I don't know what should I do . 
where is the problem ?
Help me please .
And I add this point that I check my path and I checked my file , both of them are true , there is no problem with them :(

**Comment by hebertialmeida** [comment]
> Note: I will be closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out.
