### ISSUE TITLE
How can I use pub link

### ISSUE THREAD

**Issue by WCChimiiz** [FolioReader/FolioReaderKit#373]
I want to read ePub from link, how can I do ?

I use v.1.2.0 in swift3.2 and Xcode 10

Thank you

**Comment by WCChimiiz** [comment]
and how to disable close button

**Comment by hebertialmeida** [comment]
> Note: I will be closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out.
