### ISSUE TITLE
use WKWebView?

### ISSUE THREAD

**Issue by cuipeng1976** [FolioReader/FolioReaderKit#374]
since iOS8 we got wkwebview, it's better than uiwebview,
loading performance, memory usage, and so on.
but i don't kown if somting not suitable for this project.

**Comment by hebertialmeida** [comment]
WKWebView was not implemented yet due to the lack of Pagination API, that would break the current pagination implementation. I would love to see that implemented if you use this project please help implement that.

> Note: I will be closing GH Issues on this project, I don't work full time on it and I haven't being able to update that recently, if you would like to help maintaining that and pushing the development of this project forward, just reach me out.
