### ISSUE TITLE
Epub3 with media overlay

### ISSUE THREAD

**Issue by CodeNea** [FolioReader/FolioReaderKit#375]
I have compiled an EPUB 3 book using Jotuh, and added a SMIL file to a chapter with a MP4-file. Both the SMIL file and the MP4-file are embedded within the EPUB 3 file. If I open the book in the Readium Chrome app and play the chapter, the media overlay works just fine.

But not in FolioKit, neither with Swift nor with Android. If I start playing the chapter only the TTS starts speaking, rather than playing the audio file in the Epub file.

I haven't found any resources on this or a guide how to use the media overlay, hence I thought I'll just ask here.

**Comment by hebertialmeida** [comment]
> Note: I will be closing GH Issues on this project, I don't work full time on it and I haven't been able to update that recently if you would like to help to maintain that and to push the development of this project forward, just reach me out.
