### ISSUE TITLE
The bug of  delete and copy a epubfile

### ISSUE THREAD

**Issue by uugo** [FolioReader/FolioReaderKit#44]
If I open a epub file which has 3 pages by FolioReader, and delete it.And now ,I open a epub which has 4 pages and same name . The bug will happen.This question's positon is in tableView(...cellForRowAtIndexPath...) of  FolioReaderSiderPanel.swift.

The bug line is 
 if let resource = book.spine.spineReferences[currentPageNumber-1].resource {

I guess the sqlite record the pagenumber of the epub,and this pagenumber is different with the new epub.

please give me some suggestion,thank U very much!

**Comment by kjantzer** [comment]
@uugo Interesting.

@hebertialmeida we should probably put a check to make sure the reference exists and if it does not, show the TOC view (like when a book is loaded for the first time)  I'm not sure the likelihood of this happening in a production environment, but should be a fairly simple patch.

**Comment by hebertialmeida** [comment]
@uugo Thanks for reporting! I have fixed that, please test it.

@kjantzer I have added a extension from here: http://stackoverflow.com/a/30593673/517707 to check if the item exists on array, It's safer :+1:

**Comment by uugo** [comment]
@hebertialmeida:It's OK.
