### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by bkobilansky** [FolioReader/FolioReaderKit#46]
Nice work! What are your thoughts on adding a test target? 

I see some code that could be simplified, but would like to confirm changes aren't breaking existing behavior.

**Comment by hebertialmeida** [comment]
Thanks, I think that is good to have tests, you can add it!

So, all the contributors will be benefited :+1:

**Comment by bkobilansky** [comment]
Setup and simple test in #47

**Comment by hebertialmeida** [comment]
@bkobilansky Merged, I'm looking at Quick and Nimble. If you could write some test cases would be good!

**Comment by hebertialmeida** [comment]
@bkobilansky Do you know why is not showing on Test Navigator?
![screen shot 2016-01-26 at 16 58 09](https://cloud.githubusercontent.com/assets/103670/12591268/157d3e4e-c44e-11e5-887b-ff10a4e7c6ce.png)

**Comment by bkobilansky** [comment]
Is information related to that test being printed when you run them?

As I understand it, it's because Quick adds test cases dynamically, which Xcode doesn't support very well yet. 

I believe Quick has some fixes upcoming for this, this thread discusses it fairly well:
https://github.com/Quick/Quick/issues/439

**Comment by hebertialmeida** [comment]
Yes, there is a lot of errors related to this. Do you think that even with this errors is better to use Quick instead of XCTest?

**Comment by bkobilansky** [comment]
Yes I do, personally. I prefer the syntax and consider Quick very reliable. I believe other third-party testing frameworks have issues with Xcode's test navigator as well, and I don't consider it a big deal.

Having said that, XCTest can probably handle all of our testing needs. If we feel strongly about using XCTest I wouldn't be opposed to it. The few tests we have so far would be easy to convert.

**Comment by hebertialmeida** [comment]
To be honest with you I am not an XCTest expert, if you are saying that I believe that it's be best approach.

I am learning the Quick documentation.
