### ISSUE TITLE
Sometimes the scroll bar gets stuck

### ISSUE THREAD

**Issue by CHPraxis** [FolioReader/FolioReaderKit#50]
Hello!  First, I want to say, this is a wonderful framework, and thank you very much for providing it.

I am encountering an odd bug with a document with multiple sections, each of which is maybe 7-8 paragraphs.   As I swipe through the sections, sometimes switching between flicking my finger or using the bar in the side, and then swipe down hard to the next section, sometimes the scroll bar will get stuck and not follow my location in the document as I am scrolling.  Manually moving the scroll bar will not actually scroll me when in this state as well.

Moving to the next section will sometimes reset it and fix the issue, until it occurs again.

I've been trying to reproduce the exact cause and have been unable to pinpoint it, but I can get it to occur pretty frequently by moving back and forth between sections and switching between flicks of the screen and pulling on the scrollbar.

Just wanted to make you aware- thanks!  If I knew any Swift, I'd try to help out.

**Comment by kjantzer** [comment]
Thanks @CHPraxis 
I've noticed this happening occasionally as well. I wrote that slider, but haven't had the time yet to fix that bug yet. If you figure out how to reproduce consistently, please let me know!

**Comment by anonymousRacer** [comment]
I also had this issue. The reader works great when reading english epubs, but when it comes to different languages like hindi, it gets stuck for almost 30 seconds. Also, the book cover in reader gets elongated for some reason. Would it be possible to show an activity indicator while parsing is in progress??

**Comment by hebertialmeida** [comment]
This is fixed on last versions.
