### ISSUE TITLE
Request: Improved Objective-C compatibility

### ISSUE THREAD

**Issue by CHPraxis** [FolioReader/FolioReaderKit#51]
Hello!  I've been working long term on a single project that is 99% Objective-C, so I haven't taken the time to learn Swift yet.  (I was kind of planning to hold off for Swift 3.0, but it's starting to become so prevalent that I probably should get around to it.)  Because of that, I can't exactly try to fix your code and submit a pull request for this.

When using FolioReaderKit in an Objective-C application, there's a few hiccups.  The main one is that the header doesn't make FolioReader available to the end user; the only one that becomes available to users is FolioReaderConfig.

My reading on the topic (as a person who knows no Swift) indicates that an object needs to inherit from an Objective-C class or have the @objc flag.  I see that "public class FolioReaderConfig: NSObject" inherits.

Without really knowing anything about Swift, I went in to FolioReaderKit.swift and made public class FolioReader inherit from NSObject. (Also changed the next line to "public **override** init".)

This seemed to make it workable for me; I could adjust a config and present a reader.  Though, I think I'm pretty limited in my ability to customize it.  I also don't know if this will cause any other problems down the road.

Can this be adjusted for better Objective-C compatibility in this manner?

Also: it'd be really helpful if there were a few more options in Config.  For example, I'd like to keep the menu bar always visible at the top (disable hiding), because I feel like it's really easy for the user to get lost and not realize they have to tap to get it to show up, given the rest of the layout of my app.

**Comment by kjantzer** [comment]
@CHPraxis 

If you set `shouldHideNavigationOnTap` to `false`, the menu/nav bar will always be visible.

**Comment by CHPraxis** [comment]
Hm, I can't seem to access shouldHideNavigationOnTap from my Objective-C classes.  Wonder if there's an issue with Boolean type getters and setters in Swift vs Objective-C, maybe?  Since I can change to the non-Boolean vars.

**Comment by kjantzer** [comment]
URL schemes have to be setup in the plist to work. I think that's something best done outside of the framework in your own logic.

I'm not sure about the `shouldHideNavigationOnTap` not being accessible. I'd have to look at the code more. Just switch to swift ;)

**Comment by CHPraxis** [comment]
Definitely am going to start using Swift going forward once I finish learning it, but in the meantime, it'll take forever to bring my existing Objective-C app to 100% Swift :/

I have URL schemes set up- they work fine from Safari- but when I make an ePub link containing a custom URL scheme and touch them within FolioReader, I get no action.

**Comment by kjantzer** [comment]
Ah, ok. I understand what you are talking about with URL schemes now.

I've created #52

**Comment by hebertialmeida** [comment]
This is fixed.
