### ISSUE TITLE
PDF support

### ISSUE THREAD

**Issue by ProudOfZiggy** [FolioReader/FolioReaderKit#54]
?

**Comment by hebertialmeida** [comment]
FolioReader is a ePub parser, so only ePubs are supported.

**Comment by ProudOfZiggy** [comment]
Will be a PDF support in the future? Or maybe I could fork your project and add this functional?

**Comment by hebertialmeida** [comment]
@ProudOfZiggy Interesting. What do you think @kjantzer

**Comment by kjantzer** [comment]
Yeah, interesting idea. I'm not sure how the functionality would transfer over; like chapters, highlighting, takes notes. Might be a good start to see how iBooks on iOS handles it?

Seeing a fork from @ProudOfZiggy with this feature would be a start.

**Comment by hebertialmeida** [comment]
@ProudOfZiggy If you could for and implement this I will assign it to you.

**Comment by ProudOfZiggy** [comment]
I will try, but later, I have a lot of work right now

**Comment by sibeliusseraphini** [comment]
@ProudOfZiggy this could help you - https://developer.apple.com/library/ios/samplecode/ZoomingPDFViewer/Introduction/Intro.html

**Comment by mythodeia** [comment]
pdf support would indeed be a great feature :+1:

**Comment by remisb** [comment]
PDF format is too complicated and rarely easy to achieve text reflow without complicated calculations. Are you sure you will be able to handle those problems? Are you ready to mess with that? My suggestions would be to take a closer look at pdf format and how text is positioned in it.

I'm very skeptical about possibility to have it done properly.

**Comment by zh-wowtv** [comment]
I think there are some other pdf reader already. For example, mupdf, it's quite nice.

**Comment by hebertialmeida** [comment]
I think for now we will only focus on Epub.
