### ISSUE TITLE
tvOS support?

### ISSUE THREAD

**Issue by mdilaveroglu** [FolioReader/FolioReaderKit#55]
Hi, I tried this library with tvOS but it I got a not compatible error. Are there going to be any updates about this in the future?

**Comment by hebertialmeida** [comment]
Hi @mdilaveroglu I have never tested this on tvOS, but it would be amazing if you could help adding support this on tv.

**Comment by mdilaveroglu** [comment]
After a little bit of searching, I found that tvOS does not have webview. This library is based on webviews so I have no idea how to implement this for tvOS.

**Comment by hebertialmeida** [comment]
Yes, this totally based on WebView, I don't think it will be possible.

**Comment by amosavian** [comment]
How about switching to WKWebView counterpart?

**Comment by amosavian** [comment]
@hebertialmeida How about switching to WKWebView counterpart? @mdilaveroglu

**Comment by hebertialmeida** [comment]
@amosavian In the beginning of the project I tried WKWebView, but I remember I had some problems and I decided to use UIWebView.

You can try de conversion, if you do make a Pull Request :)
