### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by fahimk** [FolioReader/FolioReaderKit#56]

**Comment by kjantzer** [comment]
FolioReader is managed with CocoaPods. Is there really a need to support [Carthage](https://github.com/Carthage/Carthage) too?

**Comment by alexpopov** [comment]
I actually need Carthage support too :( My project breaks when I `use_frameworks!` in Cocoapods, so all my Swift dependencies are in Carthage.

**Comment by alexpopov** [comment]
I might just do this myself; I had to hand-build a fat binary from the Example project, and not having Carthage support sort of precludes my ability to effectively contribute.

**Comment by hebertialmeida** [comment]
The implementation is finished by @alexpopov on PR #74, I will release it soon.
