### ISSUE TITLE
UI Lag when book is being parsed

### ISSUE THREAD

**Issue by prashantShrivastava91** [FolioReader/FolioReaderKit#57]
The reader works great when parsing english epubs, but when it comes to different languages like hindi and tamil, UI gets stuck while parsing. There is an initial UI lag when reader is being instantiated. But even after the content is loaded and I scroll fast to bottom,  UI gets stuck for a while. Also, if I scroll to top, the book cover gets elongated for some reason. Is there a way to show an activity indicator while parsing is in progress??

You can try this book to test UI lag.

[tamil book sample](https://drive.google.com/file/d/0B2f8dvJ5eSXia0VMNmlQZjVheW8/view?usp=sharing)

**Comment by hebertialmeida** [comment]
I have tested it, I will take a look..

**Comment by hebertialmeida** [comment]
This should be fixed.
