### ISSUE TITLE
arabic character

### ISSUE THREAD

**Issue by syrakozz** [FolioReader/FolioReaderKit#59]
can you plz add arabic character support

**Comment by hebertialmeida** [comment]
@syrakozz Hey what do you mean arabic character support?

I have no experience with arabic, is it possible to make a PR or help me understand what do you need?

**Comment by syrakozz** [comment]
i mean i cant open a book with arabic character

**Comment by hebertialmeida** [comment]
Can you send me this, so I can test it. Because I have opened other books with arabic character

**Comment by syrakozz** [comment]
its works tx

**Comment by credli** [comment]
@syrakozz How about sharing how you got it to work? I am facing this issue too.
