### ISSUE TITLE
Great for stimulator. Problem with iPhone 6 Plus

### ISSUE THREAD

**Issue by Huluhu** [FolioReader/FolioReaderKit#6]
App broke after LaunchScreen.
I used iPhone 6 Plus. Xcode Version 7.1.1 (7B1005). iMac 21 inch 2014. 

dyld`dyld_fatal_error:
->  0x120039088 <+0>: brk    #0x3

and in command line:

dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /var/mobile/Containers/Bundle/Application/816D7C8A-145D-4D3C-BE37-B204B6A86C8C/Example.app/Example
  Reason: no suitable image found.  Did find:
	/private/var/mobile/Containers/Bundle/Application/816D7C8A-145D-4D3C-BE37-B204B6A86C8C/Example.app/Frameworks/libswiftCore.dylib: mmap() errno=1 validating first page of '/private/var/mobile/Containers/Bundle/Application/816D7C8A-145D-4D3C-BE37-B204B6A86C8C/Example.app/Frameworks/libswiftCore.dylib'
	/private/var/mobile/Containers/Bundle/Application/816D7C8A-145D-4D3C-BE37-B204B6A86C8C/Example.app/Frameworks/libswiftCore.dylib: mmap() errno=1 validating first page of '/private/var/mobile/Containers/Bundle/Application/816D7C8A-145D-4D3C-BE37-B204B6A86C8C/Example.app/Frameworks/libswiftCore.dylib'
	/private/var/mobile/Containers/Bundle/Application/816D7C8A-145D-4D3C-BE37-B204B6A86C8C/Example.app/Frameworks/libswiftCore.dylib: mmap() errno=1 validating first page of '/private/var/mobile/Containers/Bundle/Application/816D7C8A-145D-4D3C-BE37-B204B6A86C8C/Example.app/Frameworks/libswiftCore.dylib'
(lldb)

**Comment by hebertialmeida** [comment]
It's working normally on device here, first check the last version of source, if does not work try this http://stackoverflow.com/questions/26024100/dyld-library-not-loaded-rpath-libswiftcore-dylib

**Comment by Huluhu** [comment]
Thank You!
