### ISSUE TITLE
Sample app does not work

### ISSUE THREAD

**Issue by alexeyismirnov** [FolioReader/FolioReaderKit#61]
Environment: Xcode 7.3 (7D175), simulator iPhone 4s / iOS 9.3 (13E230).

The app compiles, starts, and shows two book covers. However, when I click one of the books, it crashes. See the attached image.

![screen shot 2016-04-08 at 4 08 55 pm](https://cloud.githubusercontent.com/assets/4033296/14377799/4d57366e-fda4-11e5-8921-0e8e42759e00.png)

**Comment by mythodeia** [comment]
does it crash on device too?

**Comment by hebertialmeida** [comment]
I will take a look

**Comment by hebertialmeida** [comment]
@mythodeia and @alexeyismirnov I have pushed a new version, please test it and let me know.

**Comment by mythodeia** [comment]
same error on simulator...
```
Epub file does not exist.
fatal error: unexpectedly found nil while unwrapping an Optional value
```
works fine on device: iPhone 6S Plus IOS 9.3.1

**Comment by hebertialmeida** [comment]
@mythodeia Have you removed the App and cleaned the project?

**Comment by mythodeia** [comment]
i never had it installed in the first place but let me try it again...hold on

**Comment by mythodeia** [comment]
nope..crashes when the loading indicator appears on screen with the error mentioned above.

**Comment by hebertialmeida** [comment]
Fixing that, found the problem.

**Comment by hebertialmeida** [comment]
Fixed. I will release it
