### ISSUE TITLE
paging view feature

### ISSUE THREAD

**Issue by JackLauu** [FolioReader/FolioReaderKit#66]
Because the UIWebView inherent restraint, it can't swipe horizontal, hyphenation and text justify is also not good, can u also consider supporting these features by paging view?

**Comment by hebertialmeida** [comment]
Could you give me more details of what you need? is it related to issue #22?

**Comment by itleo31** [comment]
@hebertialmeida I though I understand what @JackLauu  meaning. Like him, I would love if you can support swipe from right to left, and new page come. It looks like iBook app.

**Comment by hebertialmeida** [comment]
This is duplicated of #22
