### ISSUE TITLE
Crash on `resetScrollDelta` after dismissing reader

### ISSUE THREAD

**Issue by alexpopov** [FolioReader/FolioReaderKit#72]
A second or so after I dismissed the player I got this crash:
```
func resetScrollDelta(){
    if scrollDeltaTimer != nil {
        scrollDeltaTimer.invalidate() // crash: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
        scrollDeltaTimer = nil
    }
    
    scrollStart = scrollView().contentOffset.y
    scrollDelta = 0
}
```
I'm not entirely sure how it's possible, but this does look like a nil access. The main thread may have been pre-empted, and perhaps `scrollDeltaTimer` was nil-ed out right after the check to whether it's nil or not. Adding explicit unwrapping might be a good idea ¯\_(ツ)_/¯ 

It's only happened once, out of dozens of times showing/dismissing the controller, so it's far from critical to figure out.

**Comment by kjantzer** [comment]
That's strange...it tests for `scrollDeltaTimer != nil` first...

**Comment by hebertialmeida** [comment]
Strange 2...

**Comment by hebertialmeida** [comment]
@kjantzer Can you check that? I have initially worked on this 😄

**Comment by kjantzer** [comment]
When I start working on this project again, sure.

**Comment by hebertialmeida** [comment]
I have tested and I could not simulate this.
