### ISSUE TITLE
Table of Contents Uncaught Exception

### ISSUE THREAD

**Issue by alexpopov** [FolioReader/FolioReaderKit#73]
In some EPUBs tapping the Table of Contents in the book itself throws a WebView exception:
`WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> attempt to scroll to invalid index path: <NSIndexPath: 0xc000000000e00016> {length = 2, path = 0 - 7}`
After which the app is permanently in a UI funk with animations where there shouldn't any, and really sluggish user interaction.

I've got [a video](https://cloudup.com/chBRUAcOBc6) of the kind of UI weirdery that happens. 
And an EPUB that has this issue. 
[A Princess of Mars.epub.zip](https://github.com/FolioReader/FolioReaderKit/files/294598/A.Princess.of.Mars.epub.zip)

It's not a very common issue, but it's appalling how many EPUBs have some issues, presumably because they're not properly made.

**Comment by hebertialmeida** [comment]
I have checked and this is not a reader problem, the main problem is the ePub standards. 

Like this crazy file names -> `@public@vhost@g@gutenberg@html@files@62@62-h@62-h-0.htm.html`

About the UI it was really crazy bug 😄. What is causing this is that the can not find the right file to point and there is a UIView animation with competition block, so the index path do not exists and the animation never finish 😭. Now I am validating the indexPath before enter on animation block, if not valid print a error.

**Comment by alexpopov** [comment]
Great, that fixed it! 

Thanks a bunch 😊
