### ISSUE TITLE
Make all required NSCoder initializers `fatalError()`

### ISSUE THREAD

**Issue by alexpopov** [FolioReader/FolioReaderKit#75]
Although this means users cannot use FolioReader classes in Interface Builder, it will allow us to change many instance properties that are Implicitly Unwrapped to be safe with no actual cost. FolioReader will most likely crash if it's initialized from NSCoder anyway, so what's the point of pandering to the compiler?

Anytime I see an exclamation mark I shiver a little bit.

**Comment by hebertialmeida** [comment]
I think that it is valid, there is not priority to Interface Builder.
