### ISSUE TITLE
Carthage CXAImageSupport timeout

### ISSUE THREAD

**Issue by danfsd** [FolioReader/FolioReaderKit#79]
While trying to run `carthage update` I'm getting the following message:
`xcodebuild timed out while trying to read Demo.xcodeproj 😭`

This may be related to #41.

It seems to be related to [UIMenuItem-CXAImageSupport](https://github.com/cxa/UIMenuItem-CXAImageSupport). Looking in to the **Carthage** issues, I realized that they have, in the recent past, fixed a timeout bug as described on [https://github.com/Carthage/Carthage/issues/1163](url), which got me worried, since I'm using the latest **Carthage** version.

**Comment by alexpopov** [comment]
I ran into this issue occasionally as well; no clue what's causing it. We expect to switch to the Swift version of UIMenuItem soon 😊

**Comment by hebertialmeida** [comment]
Probably switching to the new version of UIMenuItem can fix that.

**Comment by danfsd** [comment]
I managed to build the project by **forking** the (UIMenuItem-CXAImageSupport)[https://github.com/cxa/UIMenuItem-CXAImageSupport] and removing the `Demo.xcodeproj` from it.

If anyone has difficulties while trying to build the project, please try replacing on the `Cartfile` the line
`github "cxa/UIMenuItem-CXAImageSupport"`
`github "danfsd/UIMenuItem-CXAImageSupport"`

**Comment by hebertialmeida** [comment]
We have to migrate to https://github.com/cxa/MenuItemKit
