### ISSUE TITLE
PDF Support 

### ISSUE THREAD

**Issue by taku33** [FolioReader/FolioReaderKit#80]
this is my contributed repo.
https://github.com/taku33/FolioReaderPlus

there was a new issue about PDF
https://github.com/taku33/FolioReaderPlus/issues/1
so, someone make PDF function? I may make in someday.

**Comment by hebertialmeida** [comment]
Hey @taku33 I have seen some progress in your code, don't you want to make a Pull Request of some features like #35 and #43 

Also this is a duplicated of #54

**Comment by umarchohan** [comment]
@taku33 
can you convert your repo in swift 3 ?
