### ISSUE TITLE
How can I install another library in this Kit?

### ISSUE THREAD

**Issue by alexliubj** [FolioReader/FolioReaderKit#81]
I want to add something like a third part library into FolioReaderCenter .swift.
I'm using pods, but I don't know what should I do.
I tried to add that library into pod file and do pod update. I can see the library is installed.
When I am trying to import it from FolioReaderCenter it says can't find the module.

by the way the library is not open source and it is a framework with a few .framework and .h files.

Thanks,

**Comment by hebertialmeida** [comment]
It is really hard to discover the exactly problem, because framework embedding in Swift sometime kill you.

You can try on stackoverflow http://stackoverflow.com/questions/33796065/embedding-frameworks-inside-closed-source-swift-framework
